# -*- coding: utf-8 -*-
# Automatically generated, so don’t edit!

Expectations do
  expect 'a'.u do 'A'.u.downcase end
  expect 'b'.u do 'B'.u.downcase end
  expect 'c'.u do 'C'.u.downcase end
  expect 'd'.u do 'D'.u.downcase end
  expect 'e'.u do 'E'.u.downcase end
  expect 'f'.u do 'F'.u.downcase end
  expect 'g'.u do 'G'.u.downcase end
  expect 'h'.u do 'H'.u.downcase end
  expect 'k'.u do 'K'.u.downcase end
  expect 'l'.u do 'L'.u.downcase end
  expect 'm'.u do 'M'.u.downcase end
  expect 'n'.u do 'N'.u.downcase end
  expect 'o'.u do 'O'.u.downcase end
  expect 'p'.u do 'P'.u.downcase end
  expect 'q'.u do 'Q'.u.downcase end
  expect 'r'.u do 'R'.u.downcase end
  expect 's'.u do 'S'.u.downcase end
  expect 't'.u do 'T'.u.downcase end
  expect 'u'.u do 'U'.u.downcase end
  expect 'v'.u do 'V'.u.downcase end
  expect 'w'.u do 'W'.u.downcase end
  expect 'x'.u do 'X'.u.downcase end
  expect 'y'.u do 'Y'.u.downcase end
  expect 'z'.u do 'Z'.u.downcase end
  expect 'A'.u do 'a'.u.upcase end
  expect 'B'.u do 'b'.u.upcase end
  expect 'C'.u do 'c'.u.upcase end
  expect 'D'.u do 'd'.u.upcase end
  expect 'E'.u do 'e'.u.upcase end
  expect 'F'.u do 'f'.u.upcase end
  expect 'G'.u do 'g'.u.upcase end
  expect 'H'.u do 'h'.u.upcase end
  expect 'J'.u do 'j'.u.upcase end
  expect 'K'.u do 'k'.u.upcase end
  expect 'L'.u do 'l'.u.upcase end
  expect 'M'.u do 'm'.u.upcase end
  expect 'N'.u do 'n'.u.upcase end
  expect 'O'.u do 'o'.u.upcase end
  expect 'P'.u do 'p'.u.upcase end
  expect 'Q'.u do 'q'.u.upcase end
  expect 'R'.u do 'r'.u.upcase end
  expect 'S'.u do 's'.u.upcase end
  expect 'T'.u do 't'.u.upcase end
  expect 'U'.u do 'u'.u.upcase end
  expect 'V'.u do 'v'.u.upcase end
  expect 'W'.u do 'w'.u.upcase end
  expect 'X'.u do 'x'.u.upcase end
  expect 'Y'.u do 'y'.u.upcase end
  expect 'Z'.u do 'z'.u.upcase end
  expect 'Μ'.u do 'µ'.u.upcase end
  expect 'à'.u do 'À'.u.downcase end
  expect 'á'.u do 'Á'.u.downcase end
  expect 'â'.u do 'Â'.u.downcase end
  expect 'ã'.u do 'Ã'.u.downcase end
  expect 'ä'.u do 'Ä'.u.downcase end
  expect 'å'.u do 'Å'.u.downcase end
  expect 'æ'.u do 'Æ'.u.downcase end
  expect 'ç'.u do 'Ç'.u.downcase end
  expect 'è'.u do 'È'.u.downcase end
  expect 'é'.u do 'É'.u.downcase end
  expect 'ê'.u do 'Ê'.u.downcase end
  expect 'ë'.u do 'Ë'.u.downcase end
  expect 'î'.u do 'Î'.u.downcase end
  expect 'ï'.u do 'Ï'.u.downcase end
  expect 'ð'.u do 'Ð'.u.downcase end
  expect 'ñ'.u do 'Ñ'.u.downcase end
  expect 'ò'.u do 'Ò'.u.downcase end
  expect 'ó'.u do 'Ó'.u.downcase end
  expect 'ô'.u do 'Ô'.u.downcase end
  expect 'õ'.u do 'Õ'.u.downcase end
  expect 'ö'.u do 'Ö'.u.downcase end
  expect 'ø'.u do 'Ø'.u.downcase end
  expect 'ù'.u do 'Ù'.u.downcase end
  expect 'ú'.u do 'Ú'.u.downcase end
  expect 'û'.u do 'Û'.u.downcase end
  expect 'ü'.u do 'Ü'.u.downcase end
  expect 'ý'.u do 'Ý'.u.downcase end
  expect 'þ'.u do 'Þ'.u.downcase end
  expect 'SS'.u do 'ß'.u.upcase end
  expect 'À'.u do 'à'.u.upcase end
  expect 'Á'.u do 'á'.u.upcase end
  expect 'Â'.u do 'â'.u.upcase end
  expect 'Ã'.u do 'ã'.u.upcase end
  expect 'Ä'.u do 'ä'.u.upcase end
  expect 'Å'.u do 'å'.u.upcase end
  expect 'Æ'.u do 'æ'.u.upcase end
  expect 'Ç'.u do 'ç'.u.upcase end
  expect 'È'.u do 'è'.u.upcase end
  expect 'É'.u do 'é'.u.upcase end
  expect 'Ê'.u do 'ê'.u.upcase end
  expect 'Ë'.u do 'ë'.u.upcase end
  expect 'Ì'.u do 'ì'.u.upcase end
  expect 'Í'.u do 'í'.u.upcase end
  expect 'Î'.u do 'î'.u.upcase end
  expect 'Ï'.u do 'ï'.u.upcase end
  expect 'Ð'.u do 'ð'.u.upcase end
  expect 'Ñ'.u do 'ñ'.u.upcase end
  expect 'Ò'.u do 'ò'.u.upcase end
  expect 'Ó'.u do 'ó'.u.upcase end
  expect 'Ô'.u do 'ô'.u.upcase end
  expect 'Õ'.u do 'õ'.u.upcase end
  expect 'Ö'.u do 'ö'.u.upcase end
  expect 'Ø'.u do 'ø'.u.upcase end
  expect 'Ù'.u do 'ù'.u.upcase end
  expect 'Ú'.u do 'ú'.u.upcase end
  expect 'Û'.u do 'û'.u.upcase end
  expect 'Ü'.u do 'ü'.u.upcase end
  expect 'Ý'.u do 'ý'.u.upcase end
  expect 'Þ'.u do 'þ'.u.upcase end
  expect 'Ÿ'.u do 'ÿ'.u.upcase end
  expect 'ā'.u do 'Ā'.u.downcase end
  expect 'Ā'.u do 'ā'.u.upcase end
  expect 'ă'.u do 'Ă'.u.downcase end
  expect 'Ă'.u do 'ă'.u.upcase end
  expect 'ą'.u do 'Ą'.u.downcase end
  expect 'Ą'.u do 'ą'.u.upcase end
  expect 'ć'.u do 'Ć'.u.downcase end
  expect 'Ć'.u do 'ć'.u.upcase end
  expect 'ĉ'.u do 'Ĉ'.u.downcase end
  expect 'Ĉ'.u do 'ĉ'.u.upcase end
  expect 'ċ'.u do 'Ċ'.u.downcase end
  expect 'Ċ'.u do 'ċ'.u.upcase end
  expect 'č'.u do 'Č'.u.downcase end
  expect 'Č'.u do 'č'.u.upcase end
  expect 'ď'.u do 'Ď'.u.downcase end
  expect 'Ď'.u do 'ď'.u.upcase end
  expect 'đ'.u do 'Đ'.u.downcase end
  expect 'Đ'.u do 'đ'.u.upcase end
  expect 'ē'.u do 'Ē'.u.downcase end
  expect 'Ē'.u do 'ē'.u.upcase end
  expect 'ĕ'.u do 'Ĕ'.u.downcase end
  expect 'Ĕ'.u do 'ĕ'.u.upcase end
  expect 'ė'.u do 'Ė'.u.downcase end
  expect 'Ė'.u do 'ė'.u.upcase end
  expect 'ę'.u do 'Ę'.u.downcase end
  expect 'Ę'.u do 'ę'.u.upcase end
  expect 'ě'.u do 'Ě'.u.downcase end
  expect 'Ě'.u do 'ě'.u.upcase end
  expect 'ĝ'.u do 'Ĝ'.u.downcase end
  expect 'Ĝ'.u do 'ĝ'.u.upcase end
  expect 'ğ'.u do 'Ğ'.u.downcase end
  expect 'Ğ'.u do 'ğ'.u.upcase end
  expect 'ġ'.u do 'Ġ'.u.downcase end
  expect 'Ġ'.u do 'ġ'.u.upcase end
  expect 'ģ'.u do 'Ģ'.u.downcase end
  expect 'Ģ'.u do 'ģ'.u.upcase end
  expect 'ĥ'.u do 'Ĥ'.u.downcase end
  expect 'Ĥ'.u do 'ĥ'.u.upcase end
  expect 'ħ'.u do 'Ħ'.u.downcase end
  expect 'Ħ'.u do 'ħ'.u.upcase end
  expect 'Ĩ'.u do 'ĩ'.u.upcase end
  expect 'ī'.u do 'Ī'.u.downcase end
  expect 'Ī'.u do 'ī'.u.upcase end
  expect 'ĭ'.u do 'Ĭ'.u.downcase end
  expect 'Ĭ'.u do 'ĭ'.u.upcase end
  expect 'Į'.u do 'į'.u.upcase end
  expect 'I'.u do 'ı'.u.upcase end
  expect 'ĳ'.u do 'Ĳ'.u.downcase end
  expect 'Ĳ'.u do 'ĳ'.u.upcase end
  expect 'ĵ'.u do 'Ĵ'.u.downcase end
  expect 'Ĵ'.u do 'ĵ'.u.upcase end
  expect 'ķ'.u do 'Ķ'.u.downcase end
  expect 'Ķ'.u do 'ķ'.u.upcase end
  expect 'ĺ'.u do 'Ĺ'.u.downcase end
  expect 'Ĺ'.u do 'ĺ'.u.upcase end
  expect 'ļ'.u do 'Ļ'.u.downcase end
  expect 'Ļ'.u do 'ļ'.u.upcase end
  expect 'ľ'.u do 'Ľ'.u.downcase end
  expect 'Ľ'.u do 'ľ'.u.upcase end
  expect 'ŀ'.u do 'Ŀ'.u.downcase end
  expect 'Ŀ'.u do 'ŀ'.u.upcase end
  expect 'ł'.u do 'Ł'.u.downcase end
  expect 'Ł'.u do 'ł'.u.upcase end
  expect 'ń'.u do 'Ń'.u.downcase end
  expect 'Ń'.u do 'ń'.u.upcase end
  expect 'ņ'.u do 'Ņ'.u.downcase end
  expect 'Ņ'.u do 'ņ'.u.upcase end
  expect 'ň'.u do 'Ň'.u.downcase end
  expect 'Ň'.u do 'ň'.u.upcase end
  expect 'ʼN'.u do 'ŉ'.u.upcase end
  expect 'ŋ'.u do 'Ŋ'.u.downcase end
  expect 'Ŋ'.u do 'ŋ'.u.upcase end
  expect 'ō'.u do 'Ō'.u.downcase end
  expect 'Ō'.u do 'ō'.u.upcase end
  expect 'ŏ'.u do 'Ŏ'.u.downcase end
  expect 'Ŏ'.u do 'ŏ'.u.upcase end
  expect 'ő'.u do 'Ő'.u.downcase end
  expect 'Ő'.u do 'ő'.u.upcase end
  expect 'œ'.u do 'Œ'.u.downcase end
  expect 'Œ'.u do 'œ'.u.upcase end
  expect 'ŕ'.u do 'Ŕ'.u.downcase end
  expect 'Ŕ'.u do 'ŕ'.u.upcase end
  expect 'ŗ'.u do 'Ŗ'.u.downcase end
  expect 'Ŗ'.u do 'ŗ'.u.upcase end
  expect 'ř'.u do 'Ř'.u.downcase end
  expect 'Ř'.u do 'ř'.u.upcase end
  expect 'ś'.u do 'Ś'.u.downcase end
  expect 'Ś'.u do 'ś'.u.upcase end
  expect 'ŝ'.u do 'Ŝ'.u.downcase end
  expect 'Ŝ'.u do 'ŝ'.u.upcase end
  expect 'ş'.u do 'Ş'.u.downcase end
  expect 'Ş'.u do 'ş'.u.upcase end
  expect 'š'.u do 'Š'.u.downcase end
  expect 'Š'.u do 'š'.u.upcase end
  expect 'ţ'.u do 'Ţ'.u.downcase end
  expect 'Ţ'.u do 'ţ'.u.upcase end
  expect 'ť'.u do 'Ť'.u.downcase end
  expect 'Ť'.u do 'ť'.u.upcase end
  expect 'ŧ'.u do 'Ŧ'.u.downcase end
  expect 'Ŧ'.u do 'ŧ'.u.upcase end
  expect 'ũ'.u do 'Ũ'.u.downcase end
  expect 'Ũ'.u do 'ũ'.u.upcase end
  expect 'ū'.u do 'Ū'.u.downcase end
  expect 'Ū'.u do 'ū'.u.upcase end
  expect 'ŭ'.u do 'Ŭ'.u.downcase end
  expect 'Ŭ'.u do 'ŭ'.u.upcase end
  expect 'ů'.u do 'Ů'.u.downcase end
  expect 'Ů'.u do 'ů'.u.upcase end
  expect 'ű'.u do 'Ű'.u.downcase end
  expect 'Ű'.u do 'ű'.u.upcase end
  expect 'ų'.u do 'Ų'.u.downcase end
  expect 'Ų'.u do 'ų'.u.upcase end
  expect 'ŵ'.u do 'Ŵ'.u.downcase end
  expect 'Ŵ'.u do 'ŵ'.u.upcase end
  expect 'ŷ'.u do 'Ŷ'.u.downcase end
  expect 'Ŷ'.u do 'ŷ'.u.upcase end
  expect 'ÿ'.u do 'Ÿ'.u.downcase end
  expect 'ź'.u do 'Ź'.u.downcase end
  expect 'Ź'.u do 'ź'.u.upcase end
  expect 'ż'.u do 'Ż'.u.downcase end
  expect 'Ż'.u do 'ż'.u.upcase end
  expect 'ž'.u do 'Ž'.u.downcase end
  expect 'Ž'.u do 'ž'.u.upcase end
  expect 'S'.u do 'ſ'.u.upcase end
  expect 'Ƀ'.u do 'ƀ'.u.upcase end
  expect 'ɓ'.u do 'Ɓ'.u.downcase end
  expect 'ƃ'.u do 'Ƃ'.u.downcase end
  expect 'Ƃ'.u do 'ƃ'.u.upcase end
  expect 'ƅ'.u do 'Ƅ'.u.downcase end
  expect 'Ƅ'.u do 'ƅ'.u.upcase end
  expect 'ɔ'.u do 'Ɔ'.u.downcase end
  expect 'ƈ'.u do 'Ƈ'.u.downcase end
  expect 'Ƈ'.u do 'ƈ'.u.upcase end
  expect 'ɖ'.u do 'Ɖ'.u.downcase end
  expect 'ɗ'.u do 'Ɗ'.u.downcase end
  expect 'ƌ'.u do 'Ƌ'.u.downcase end
  expect 'Ƌ'.u do 'ƌ'.u.upcase end
  expect 'ǝ'.u do 'Ǝ'.u.downcase end
  expect 'ə'.u do 'Ə'.u.downcase end
  expect 'ɛ'.u do 'Ɛ'.u.downcase end
  expect 'ƒ'.u do 'Ƒ'.u.downcase end
  expect 'Ƒ'.u do 'ƒ'.u.upcase end
  expect 'ɠ'.u do 'Ɠ'.u.downcase end
  expect 'ɣ'.u do 'Ɣ'.u.downcase end
  expect 'Ƕ'.u do 'ƕ'.u.upcase end
  expect 'ɩ'.u do 'Ɩ'.u.downcase end
  expect 'ɨ'.u do 'Ɨ'.u.downcase end
  expect 'ƙ'.u do 'Ƙ'.u.downcase end
  expect 'Ƙ'.u do 'ƙ'.u.upcase end
  expect 'Ƚ'.u do 'ƚ'.u.upcase end
  expect 'ɯ'.u do 'Ɯ'.u.downcase end
  expect 'ɲ'.u do 'Ɲ'.u.downcase end
  expect 'Ƞ'.u do 'ƞ'.u.upcase end
  expect 'ɵ'.u do 'Ɵ'.u.downcase end
  expect 'ơ'.u do 'Ơ'.u.downcase end
  expect 'Ơ'.u do 'ơ'.u.upcase end
  expect 'ƣ'.u do 'Ƣ'.u.downcase end
  expect 'Ƣ'.u do 'ƣ'.u.upcase end
  expect 'ƥ'.u do 'Ƥ'.u.downcase end
  expect 'Ƥ'.u do 'ƥ'.u.upcase end
  expect 'ʀ'.u do 'Ʀ'.u.downcase end
  expect 'ƨ'.u do 'Ƨ'.u.downcase end
  expect 'Ƨ'.u do 'ƨ'.u.upcase end
  expect 'ʃ'.u do 'Ʃ'.u.downcase end
  expect 'ƭ'.u do 'Ƭ'.u.downcase end
  expect 'Ƭ'.u do 'ƭ'.u.upcase end
  expect 'ʈ'.u do 'Ʈ'.u.downcase end
  expect 'ư'.u do 'Ư'.u.downcase end
  expect 'Ư'.u do 'ư'.u.upcase end
  expect 'ʊ'.u do 'Ʊ'.u.downcase end
  expect 'ʋ'.u do 'Ʋ'.u.downcase end
  expect 'ƴ'.u do 'Ƴ'.u.downcase end
  expect 'Ƴ'.u do 'ƴ'.u.upcase end
  expect 'ƶ'.u do 'Ƶ'.u.downcase end
  expect 'Ƶ'.u do 'ƶ'.u.upcase end
  expect 'ʒ'.u do 'Ʒ'.u.downcase end
  expect 'ƹ'.u do 'Ƹ'.u.downcase end
  expect 'Ƹ'.u do 'ƹ'.u.upcase end
  expect 'ƽ'.u do 'Ƽ'.u.downcase end
  expect 'Ƽ'.u do 'ƽ'.u.upcase end
  expect 'Ƿ'.u do 'ƿ'.u.upcase end
  expect 'ǆ'.u do 'Ǆ'.u.downcase end
  expect 'Ǆ'.u do 'ǅ'.u.upcase end
  expect 'ǆ'.u do 'ǅ'.u.downcase end
  expect 'Ǆ'.u do 'ǆ'.u.upcase end
  expect 'ǉ'.u do 'Ǉ'.u.downcase end
  expect 'Ǉ'.u do 'ǈ'.u.upcase end
  expect 'ǉ'.u do 'ǈ'.u.downcase end
  expect 'Ǉ'.u do 'ǉ'.u.upcase end
  expect 'ǌ'.u do 'Ǌ'.u.downcase end
  expect 'Ǌ'.u do 'ǋ'.u.upcase end
  expect 'ǌ'.u do 'ǋ'.u.downcase end
  expect 'Ǌ'.u do 'ǌ'.u.upcase end
  expect 'ǎ'.u do 'Ǎ'.u.downcase end
  expect 'Ǎ'.u do 'ǎ'.u.upcase end
  expect 'ǐ'.u do 'Ǐ'.u.downcase end
  expect 'Ǐ'.u do 'ǐ'.u.upcase end
  expect 'ǒ'.u do 'Ǒ'.u.downcase end
  expect 'Ǒ'.u do 'ǒ'.u.upcase end
  expect 'ǔ'.u do 'Ǔ'.u.downcase end
  expect 'Ǔ'.u do 'ǔ'.u.upcase end
  expect 'ǖ'.u do 'Ǖ'.u.downcase end
  expect 'Ǖ'.u do 'ǖ'.u.upcase end
  expect 'ǘ'.u do 'Ǘ'.u.downcase end
  expect 'Ǘ'.u do 'ǘ'.u.upcase end
  expect 'ǚ'.u do 'Ǚ'.u.downcase end
  expect 'Ǚ'.u do 'ǚ'.u.upcase end
  expect 'ǜ'.u do 'Ǜ'.u.downcase end
  expect 'Ǜ'.u do 'ǜ'.u.upcase end
  expect 'Ǝ'.u do 'ǝ'.u.upcase end
  expect 'ǟ'.u do 'Ǟ'.u.downcase end
  expect 'Ǟ'.u do 'ǟ'.u.upcase end
  expect 'ǡ'.u do 'Ǡ'.u.downcase end
  expect 'Ǡ'.u do 'ǡ'.u.upcase end
  expect 'ǣ'.u do 'Ǣ'.u.downcase end
  expect 'Ǣ'.u do 'ǣ'.u.upcase end
  expect 'ǥ'.u do 'Ǥ'.u.downcase end
  expect 'Ǥ'.u do 'ǥ'.u.upcase end
  expect 'ǧ'.u do 'Ǧ'.u.downcase end
  expect 'Ǧ'.u do 'ǧ'.u.upcase end
  expect 'ǩ'.u do 'Ǩ'.u.downcase end
  expect 'Ǩ'.u do 'ǩ'.u.upcase end
  expect 'ǫ'.u do 'Ǫ'.u.downcase end
  expect 'Ǫ'.u do 'ǫ'.u.upcase end
  expect 'ǭ'.u do 'Ǭ'.u.downcase end
  expect 'Ǭ'.u do 'ǭ'.u.upcase end
  expect 'ǯ'.u do 'Ǯ'.u.downcase end
  expect 'Ǯ'.u do 'ǯ'.u.upcase end
  expect 'J̌'.u do 'ǰ'.u.upcase end
  expect 'ǳ'.u do 'Ǳ'.u.downcase end
  expect 'Ǳ'.u do 'ǲ'.u.upcase end
  expect 'ǳ'.u do 'ǲ'.u.downcase end
  expect 'Ǳ'.u do 'ǳ'.u.upcase end
  expect 'ǵ'.u do 'Ǵ'.u.downcase end
  expect 'Ǵ'.u do 'ǵ'.u.upcase end
  expect 'ƕ'.u do 'Ƕ'.u.downcase end
  expect 'ƿ'.u do 'Ƿ'.u.downcase end
  expect 'ǹ'.u do 'Ǹ'.u.downcase end
  expect 'Ǹ'.u do 'ǹ'.u.upcase end
  expect 'ǻ'.u do 'Ǻ'.u.downcase end
  expect 'Ǻ'.u do 'ǻ'.u.upcase end
  expect 'ǽ'.u do 'Ǽ'.u.downcase end
  expect 'Ǽ'.u do 'ǽ'.u.upcase end
  expect 'ǿ'.u do 'Ǿ'.u.downcase end
  expect 'Ǿ'.u do 'ǿ'.u.upcase end
  expect 'ȁ'.u do 'Ȁ'.u.downcase end
  expect 'Ȁ'.u do 'ȁ'.u.upcase end
  expect 'ȃ'.u do 'Ȃ'.u.downcase end
  expect 'Ȃ'.u do 'ȃ'.u.upcase end
  expect 'ȅ'.u do 'Ȅ'.u.downcase end
  expect 'Ȅ'.u do 'ȅ'.u.upcase end
  expect 'ȇ'.u do 'Ȇ'.u.downcase end
  expect 'Ȇ'.u do 'ȇ'.u.upcase end
  expect 'ȉ'.u do 'Ȉ'.u.downcase end
  expect 'Ȉ'.u do 'ȉ'.u.upcase end
  expect 'ȋ'.u do 'Ȋ'.u.downcase end
  expect 'Ȋ'.u do 'ȋ'.u.upcase end
  expect 'ȍ'.u do 'Ȍ'.u.downcase end
  expect 'Ȍ'.u do 'ȍ'.u.upcase end
  expect 'ȏ'.u do 'Ȏ'.u.downcase end
  expect 'Ȏ'.u do 'ȏ'.u.upcase end
  expect 'ȑ'.u do 'Ȑ'.u.downcase end
  expect 'Ȑ'.u do 'ȑ'.u.upcase end
  expect 'ȓ'.u do 'Ȓ'.u.downcase end
  expect 'Ȓ'.u do 'ȓ'.u.upcase end
  expect 'ȕ'.u do 'Ȕ'.u.downcase end
  expect 'Ȕ'.u do 'ȕ'.u.upcase end
  expect 'ȗ'.u do 'Ȗ'.u.downcase end
  expect 'Ȗ'.u do 'ȗ'.u.upcase end
  expect 'ș'.u do 'Ș'.u.downcase end
  expect 'Ș'.u do 'ș'.u.upcase end
  expect 'ț'.u do 'Ț'.u.downcase end
  expect 'Ț'.u do 'ț'.u.upcase end
  expect 'ȝ'.u do 'Ȝ'.u.downcase end
  expect 'Ȝ'.u do 'ȝ'.u.upcase end
  expect 'ȟ'.u do 'Ȟ'.u.downcase end
  expect 'Ȟ'.u do 'ȟ'.u.upcase end
  expect 'ƞ'.u do 'Ƞ'.u.downcase end
  expect 'ȣ'.u do 'Ȣ'.u.downcase end
  expect 'Ȣ'.u do 'ȣ'.u.upcase end
  expect 'ȥ'.u do 'Ȥ'.u.downcase end
  expect 'Ȥ'.u do 'ȥ'.u.upcase end
  expect 'ȧ'.u do 'Ȧ'.u.downcase end
  expect 'Ȧ'.u do 'ȧ'.u.upcase end
  expect 'ȩ'.u do 'Ȩ'.u.downcase end
  expect 'Ȩ'.u do 'ȩ'.u.upcase end
  expect 'ȫ'.u do 'Ȫ'.u.downcase end
  expect 'Ȫ'.u do 'ȫ'.u.upcase end
  expect 'ȭ'.u do 'Ȭ'.u.downcase end
  expect 'Ȭ'.u do 'ȭ'.u.upcase end
  expect 'ȯ'.u do 'Ȯ'.u.downcase end
  expect 'Ȯ'.u do 'ȯ'.u.upcase end
  expect 'ȱ'.u do 'Ȱ'.u.downcase end
  expect 'Ȱ'.u do 'ȱ'.u.upcase end
  expect 'ȳ'.u do 'Ȳ'.u.downcase end
  expect 'Ȳ'.u do 'ȳ'.u.upcase end
  expect 'ⱥ'.u do 'Ⱥ'.u.downcase end
  expect 'ȼ'.u do 'Ȼ'.u.downcase end
  expect 'Ȼ'.u do 'ȼ'.u.upcase end
  expect 'ƚ'.u do 'Ƚ'.u.downcase end
  expect 'ⱦ'.u do 'Ⱦ'.u.downcase end
  expect 'ɂ'.u do 'Ɂ'.u.downcase end
  expect 'Ɂ'.u do 'ɂ'.u.upcase end
  expect 'ƀ'.u do 'Ƀ'.u.downcase end
  expect 'ʉ'.u do 'Ʉ'.u.downcase end
  expect 'ʌ'.u do 'Ʌ'.u.downcase end
  expect 'ɇ'.u do 'Ɇ'.u.downcase end
  expect 'Ɇ'.u do 'ɇ'.u.upcase end
  expect 'ɉ'.u do 'Ɉ'.u.downcase end
  expect 'Ɉ'.u do 'ɉ'.u.upcase end
  expect 'ɋ'.u do 'Ɋ'.u.downcase end
  expect 'Ɋ'.u do 'ɋ'.u.upcase end
  expect 'ɍ'.u do 'Ɍ'.u.downcase end
  expect 'Ɍ'.u do 'ɍ'.u.upcase end
  expect 'ɏ'.u do 'Ɏ'.u.downcase end
  expect 'Ɏ'.u do 'ɏ'.u.upcase end
  expect 'Ɓ'.u do 'ɓ'.u.upcase end
  expect 'Ɔ'.u do 'ɔ'.u.upcase end
  expect 'Ɖ'.u do 'ɖ'.u.upcase end
  expect 'Ɗ'.u do 'ɗ'.u.upcase end
  expect 'Ə'.u do 'ə'.u.upcase end
  expect 'Ɛ'.u do 'ɛ'.u.upcase end
  expect 'Ɠ'.u do 'ɠ'.u.upcase end
  expect 'Ɣ'.u do 'ɣ'.u.upcase end
  expect 'Ɨ'.u do 'ɨ'.u.upcase end
  expect 'Ɩ'.u do 'ɩ'.u.upcase end
  expect 'Ɫ'.u do 'ɫ'.u.upcase end
  expect 'Ɯ'.u do 'ɯ'.u.upcase end
  expect 'Ɲ'.u do 'ɲ'.u.upcase end
  expect 'Ɵ'.u do 'ɵ'.u.upcase end
  expect 'Ɽ'.u do 'ɽ'.u.upcase end
  expect 'Ʀ'.u do 'ʀ'.u.upcase end
  expect 'Ʃ'.u do 'ʃ'.u.upcase end
  expect 'Ʈ'.u do 'ʈ'.u.upcase end
  expect 'Ʉ'.u do 'ʉ'.u.upcase end
  expect 'Ʊ'.u do 'ʊ'.u.upcase end
  expect 'Ʋ'.u do 'ʋ'.u.upcase end
  expect 'Ʌ'.u do 'ʌ'.u.upcase end
  expect 'Ʒ'.u do 'ʒ'.u.upcase end
  expect 'Ͻ'.u do 'ͻ'.u.upcase end
  expect 'Ͼ'.u do 'ͼ'.u.upcase end
  expect 'Ͽ'.u do 'ͽ'.u.upcase end
  expect 'ά'.u do 'Ά'.u.downcase end
  expect 'έ'.u do 'Έ'.u.downcase end
  expect 'ή'.u do 'Ή'.u.downcase end
  expect 'ί'.u do 'Ί'.u.downcase end
  expect 'ό'.u do 'Ό'.u.downcase end
  expect 'ύ'.u do 'Ύ'.u.downcase end
  expect 'ώ'.u do 'Ώ'.u.downcase end
  expect 'Ϊ́'.u do 'ΐ'.u.upcase end
  expect 'α'.u do 'Α'.u.downcase end
  expect 'β'.u do 'Β'.u.downcase end
  expect 'γ'.u do 'Γ'.u.downcase end
  expect 'δ'.u do 'Δ'.u.downcase end
  expect 'ε'.u do 'Ε'.u.downcase end
  expect 'ζ'.u do 'Ζ'.u.downcase end
  expect 'η'.u do 'Η'.u.downcase end
  expect 'θ'.u do 'Θ'.u.downcase end
  expect 'ι'.u do 'Ι'.u.downcase end
  expect 'κ'.u do 'Κ'.u.downcase end
  expect 'λ'.u do 'Λ'.u.downcase end
  expect 'μ'.u do 'Μ'.u.downcase end
  expect 'ν'.u do 'Ν'.u.downcase end
  expect 'ξ'.u do 'Ξ'.u.downcase end
  expect 'ο'.u do 'Ο'.u.downcase end
  expect 'π'.u do 'Π'.u.downcase end
  expect 'ρ'.u do 'Ρ'.u.downcase end
  expect 'τ'.u do 'Τ'.u.downcase end
  expect 'υ'.u do 'Υ'.u.downcase end
  expect 'φ'.u do 'Φ'.u.downcase end
  expect 'χ'.u do 'Χ'.u.downcase end
  expect 'ψ'.u do 'Ψ'.u.downcase end
  expect 'ω'.u do 'Ω'.u.downcase end
  expect 'ϊ'.u do 'Ϊ'.u.downcase end
  expect 'ϋ'.u do 'Ϋ'.u.downcase end
  expect 'Ά'.u do 'ά'.u.upcase end
  expect 'Έ'.u do 'έ'.u.upcase end
  expect 'Ή'.u do 'ή'.u.upcase end
  expect 'Ί'.u do 'ί'.u.upcase end
  expect 'Ϋ́'.u do 'ΰ'.u.upcase end
  expect 'Α'.u do 'α'.u.upcase end
  expect 'Β'.u do 'β'.u.upcase end
  expect 'Γ'.u do 'γ'.u.upcase end
  expect 'Δ'.u do 'δ'.u.upcase end
  expect 'Ε'.u do 'ε'.u.upcase end
  expect 'Ζ'.u do 'ζ'.u.upcase end
  expect 'Η'.u do 'η'.u.upcase end
  expect 'Θ'.u do 'θ'.u.upcase end
  expect 'Ι'.u do 'ι'.u.upcase end
  expect 'Κ'.u do 'κ'.u.upcase end
  expect 'Λ'.u do 'λ'.u.upcase end
  expect 'Μ'.u do 'μ'.u.upcase end
  expect 'Ν'.u do 'ν'.u.upcase end
  expect 'Ξ'.u do 'ξ'.u.upcase end
  expect 'Ο'.u do 'ο'.u.upcase end
  expect 'Π'.u do 'π'.u.upcase end
  expect 'Ρ'.u do 'ρ'.u.upcase end
  expect 'Σ'.u do 'ς'.u.upcase end
  expect 'Σ'.u do 'σ'.u.upcase end
  expect 'Τ'.u do 'τ'.u.upcase end
  expect 'Υ'.u do 'υ'.u.upcase end
  expect 'Φ'.u do 'φ'.u.upcase end
  expect 'Χ'.u do 'χ'.u.upcase end
  expect 'Ψ'.u do 'ψ'.u.upcase end
  expect 'Ω'.u do 'ω'.u.upcase end
  expect 'Ϊ'.u do 'ϊ'.u.upcase end
  expect 'Ϋ'.u do 'ϋ'.u.upcase end
  expect 'Ό'.u do 'ό'.u.upcase end
  expect 'Ύ'.u do 'ύ'.u.upcase end
  expect 'Ώ'.u do 'ώ'.u.upcase end
  expect 'Β'.u do 'ϐ'.u.upcase end
  expect 'Θ'.u do 'ϑ'.u.upcase end
  expect 'Φ'.u do 'ϕ'.u.upcase end
  expect 'Π'.u do 'ϖ'.u.upcase end
  expect 'ϙ'.u do 'Ϙ'.u.downcase end
  expect 'Ϙ'.u do 'ϙ'.u.upcase end
  expect 'ϛ'.u do 'Ϛ'.u.downcase end
  expect 'Ϛ'.u do 'ϛ'.u.upcase end
  expect 'ϝ'.u do 'Ϝ'.u.downcase end
  expect 'Ϝ'.u do 'ϝ'.u.upcase end
  expect 'ϟ'.u do 'Ϟ'.u.downcase end
  expect 'Ϟ'.u do 'ϟ'.u.upcase end
  expect 'ϡ'.u do 'Ϡ'.u.downcase end
  expect 'Ϡ'.u do 'ϡ'.u.upcase end
  expect 'ϣ'.u do 'Ϣ'.u.downcase end
  expect 'Ϣ'.u do 'ϣ'.u.upcase end
  expect 'ϥ'.u do 'Ϥ'.u.downcase end
  expect 'Ϥ'.u do 'ϥ'.u.upcase end
  expect 'ϧ'.u do 'Ϧ'.u.downcase end
  expect 'Ϧ'.u do 'ϧ'.u.upcase end
  expect 'ϩ'.u do 'Ϩ'.u.downcase end
  expect 'Ϩ'.u do 'ϩ'.u.upcase end
  expect 'ϫ'.u do 'Ϫ'.u.downcase end
  expect 'Ϫ'.u do 'ϫ'.u.upcase end
  expect 'ϭ'.u do 'Ϭ'.u.downcase end
  expect 'Ϭ'.u do 'ϭ'.u.upcase end
  expect 'ϯ'.u do 'Ϯ'.u.downcase end
  expect 'Ϯ'.u do 'ϯ'.u.upcase end
  expect 'Κ'.u do 'ϰ'.u.upcase end
  expect 'Ρ'.u do 'ϱ'.u.upcase end
  expect 'Ϲ'.u do 'ϲ'.u.upcase end
  expect 'θ'.u do 'ϴ'.u.downcase end
  expect 'Ε'.u do 'ϵ'.u.upcase end
  expect 'ϸ'.u do 'Ϸ'.u.downcase end
  expect 'Ϸ'.u do 'ϸ'.u.upcase end
  expect 'ϲ'.u do 'Ϲ'.u.downcase end
  expect 'ϻ'.u do 'Ϻ'.u.downcase end
  expect 'Ϻ'.u do 'ϻ'.u.upcase end
  expect 'ͻ'.u do 'Ͻ'.u.downcase end
  expect 'ͼ'.u do 'Ͼ'.u.downcase end
  expect 'ͽ'.u do 'Ͽ'.u.downcase end
  expect 'ѐ'.u do 'Ѐ'.u.downcase end
  expect 'ё'.u do 'Ё'.u.downcase end
  expect 'ђ'.u do 'Ђ'.u.downcase end
  expect 'ѓ'.u do 'Ѓ'.u.downcase end
  expect 'є'.u do 'Є'.u.downcase end
  expect 'ѕ'.u do 'Ѕ'.u.downcase end
  expect 'і'.u do 'І'.u.downcase end
  expect 'ї'.u do 'Ї'.u.downcase end
  expect 'ј'.u do 'Ј'.u.downcase end
  expect 'љ'.u do 'Љ'.u.downcase end
  expect 'њ'.u do 'Њ'.u.downcase end
  expect 'ћ'.u do 'Ћ'.u.downcase end
  expect 'ќ'.u do 'Ќ'.u.downcase end
  expect 'ѝ'.u do 'Ѝ'.u.downcase end
  expect 'ў'.u do 'Ў'.u.downcase end
  expect 'џ'.u do 'Џ'.u.downcase end
  expect 'а'.u do 'А'.u.downcase end
  expect 'б'.u do 'Б'.u.downcase end
  expect 'в'.u do 'В'.u.downcase end
  expect 'г'.u do 'Г'.u.downcase end
  expect 'д'.u do 'Д'.u.downcase end
  expect 'е'.u do 'Е'.u.downcase end
  expect 'ж'.u do 'Ж'.u.downcase end
  expect 'з'.u do 'З'.u.downcase end
  expect 'и'.u do 'И'.u.downcase end
  expect 'й'.u do 'Й'.u.downcase end
  expect 'к'.u do 'К'.u.downcase end
  expect 'л'.u do 'Л'.u.downcase end
  expect 'м'.u do 'М'.u.downcase end
  expect 'н'.u do 'Н'.u.downcase end
  expect 'о'.u do 'О'.u.downcase end
  expect 'п'.u do 'П'.u.downcase end
  expect 'р'.u do 'Р'.u.downcase end
  expect 'с'.u do 'С'.u.downcase end
  expect 'т'.u do 'Т'.u.downcase end
  expect 'у'.u do 'У'.u.downcase end
  expect 'ф'.u do 'Ф'.u.downcase end
  expect 'х'.u do 'Х'.u.downcase end
  expect 'ц'.u do 'Ц'.u.downcase end
  expect 'ч'.u do 'Ч'.u.downcase end
  expect 'ш'.u do 'Ш'.u.downcase end
  expect 'щ'.u do 'Щ'.u.downcase end
  expect 'ъ'.u do 'Ъ'.u.downcase end
  expect 'ы'.u do 'Ы'.u.downcase end
  expect 'ь'.u do 'Ь'.u.downcase end
  expect 'э'.u do 'Э'.u.downcase end
  expect 'ю'.u do 'Ю'.u.downcase end
  expect 'я'.u do 'Я'.u.downcase end
  expect 'А'.u do 'а'.u.upcase end
  expect 'Б'.u do 'б'.u.upcase end
  expect 'В'.u do 'в'.u.upcase end
  expect 'Г'.u do 'г'.u.upcase end
  expect 'Д'.u do 'д'.u.upcase end
  expect 'Е'.u do 'е'.u.upcase end
  expect 'Ж'.u do 'ж'.u.upcase end
  expect 'З'.u do 'з'.u.upcase end
  expect 'И'.u do 'и'.u.upcase end
  expect 'Й'.u do 'й'.u.upcase end
  expect 'К'.u do 'к'.u.upcase end
  expect 'Л'.u do 'л'.u.upcase end
  expect 'М'.u do 'м'.u.upcase end
  expect 'Н'.u do 'н'.u.upcase end
  expect 'О'.u do 'о'.u.upcase end
  expect 'П'.u do 'п'.u.upcase end
  expect 'Р'.u do 'р'.u.upcase end
  expect 'С'.u do 'с'.u.upcase end
  expect 'Т'.u do 'т'.u.upcase end
  expect 'У'.u do 'у'.u.upcase end
  expect 'Ф'.u do 'ф'.u.upcase end
  expect 'Х'.u do 'х'.u.upcase end
  expect 'Ц'.u do 'ц'.u.upcase end
  expect 'Ч'.u do 'ч'.u.upcase end
  expect 'Ш'.u do 'ш'.u.upcase end
  expect 'Щ'.u do 'щ'.u.upcase end
  expect 'Ъ'.u do 'ъ'.u.upcase end
  expect 'Ы'.u do 'ы'.u.upcase end
  expect 'Ь'.u do 'ь'.u.upcase end
  expect 'Э'.u do 'э'.u.upcase end
  expect 'Ю'.u do 'ю'.u.upcase end
  expect 'Я'.u do 'я'.u.upcase end
  expect 'Ѐ'.u do 'ѐ'.u.upcase end
  expect 'Ё'.u do 'ё'.u.upcase end
  expect 'Ђ'.u do 'ђ'.u.upcase end
  expect 'Ѓ'.u do 'ѓ'.u.upcase end
  expect 'Є'.u do 'є'.u.upcase end
  expect 'Ѕ'.u do 'ѕ'.u.upcase end
  expect 'І'.u do 'і'.u.upcase end
  expect 'Ї'.u do 'ї'.u.upcase end
  expect 'Ј'.u do 'ј'.u.upcase end
  expect 'Љ'.u do 'љ'.u.upcase end
  expect 'Њ'.u do 'њ'.u.upcase end
  expect 'Ћ'.u do 'ћ'.u.upcase end
  expect 'Ќ'.u do 'ќ'.u.upcase end
  expect 'Ѝ'.u do 'ѝ'.u.upcase end
  expect 'Ў'.u do 'ў'.u.upcase end
  expect 'Џ'.u do 'џ'.u.upcase end
  expect 'ѡ'.u do 'Ѡ'.u.downcase end
  expect 'Ѡ'.u do 'ѡ'.u.upcase end
  expect 'ѣ'.u do 'Ѣ'.u.downcase end
  expect 'Ѣ'.u do 'ѣ'.u.upcase end
  expect 'ѥ'.u do 'Ѥ'.u.downcase end
  expect 'Ѥ'.u do 'ѥ'.u.upcase end
  expect 'ѧ'.u do 'Ѧ'.u.downcase end
  expect 'Ѧ'.u do 'ѧ'.u.upcase end
  expect 'ѩ'.u do 'Ѩ'.u.downcase end
  expect 'Ѩ'.u do 'ѩ'.u.upcase end
  expect 'ѫ'.u do 'Ѫ'.u.downcase end
  expect 'Ѫ'.u do 'ѫ'.u.upcase end
  expect 'ѭ'.u do 'Ѭ'.u.downcase end
  expect 'Ѭ'.u do 'ѭ'.u.upcase end
  expect 'ѯ'.u do 'Ѯ'.u.downcase end
  expect 'Ѯ'.u do 'ѯ'.u.upcase end
  expect 'ѱ'.u do 'Ѱ'.u.downcase end
  expect 'Ѱ'.u do 'ѱ'.u.upcase end
  expect 'ѳ'.u do 'Ѳ'.u.downcase end
  expect 'Ѳ'.u do 'ѳ'.u.upcase end
  expect 'ѵ'.u do 'Ѵ'.u.downcase end
  expect 'Ѵ'.u do 'ѵ'.u.upcase end
  expect 'ѷ'.u do 'Ѷ'.u.downcase end
  expect 'Ѷ'.u do 'ѷ'.u.upcase end
  expect 'ѹ'.u do 'Ѹ'.u.downcase end
  expect 'Ѹ'.u do 'ѹ'.u.upcase end
  expect 'ѻ'.u do 'Ѻ'.u.downcase end
  expect 'Ѻ'.u do 'ѻ'.u.upcase end
  expect 'ѽ'.u do 'Ѽ'.u.downcase end
  expect 'Ѽ'.u do 'ѽ'.u.upcase end
  expect 'ѿ'.u do 'Ѿ'.u.downcase end
  expect 'Ѿ'.u do 'ѿ'.u.upcase end
  expect 'ҁ'.u do 'Ҁ'.u.downcase end
  expect 'Ҁ'.u do 'ҁ'.u.upcase end
  expect 'ҋ'.u do 'Ҋ'.u.downcase end
  expect 'Ҋ'.u do 'ҋ'.u.upcase end
  expect 'ҍ'.u do 'Ҍ'.u.downcase end
  expect 'Ҍ'.u do 'ҍ'.u.upcase end
  expect 'ҏ'.u do 'Ҏ'.u.downcase end
  expect 'Ҏ'.u do 'ҏ'.u.upcase end
  expect 'ґ'.u do 'Ґ'.u.downcase end
  expect 'Ґ'.u do 'ґ'.u.upcase end
  expect 'ғ'.u do 'Ғ'.u.downcase end
  expect 'Ғ'.u do 'ғ'.u.upcase end
  expect 'ҕ'.u do 'Ҕ'.u.downcase end
  expect 'Ҕ'.u do 'ҕ'.u.upcase end
  expect 'җ'.u do 'Җ'.u.downcase end
  expect 'Җ'.u do 'җ'.u.upcase end
  expect 'ҙ'.u do 'Ҙ'.u.downcase end
  expect 'Ҙ'.u do 'ҙ'.u.upcase end
  expect 'қ'.u do 'Қ'.u.downcase end
  expect 'Қ'.u do 'қ'.u.upcase end
  expect 'ҝ'.u do 'Ҝ'.u.downcase end
  expect 'Ҝ'.u do 'ҝ'.u.upcase end
  expect 'ҟ'.u do 'Ҟ'.u.downcase end
  expect 'Ҟ'.u do 'ҟ'.u.upcase end
  expect 'ҡ'.u do 'Ҡ'.u.downcase end
  expect 'Ҡ'.u do 'ҡ'.u.upcase end
  expect 'ң'.u do 'Ң'.u.downcase end
  expect 'Ң'.u do 'ң'.u.upcase end
  expect 'ҥ'.u do 'Ҥ'.u.downcase end
  expect 'Ҥ'.u do 'ҥ'.u.upcase end
  expect 'ҧ'.u do 'Ҧ'.u.downcase end
  expect 'Ҧ'.u do 'ҧ'.u.upcase end
  expect 'ҩ'.u do 'Ҩ'.u.downcase end
  expect 'Ҩ'.u do 'ҩ'.u.upcase end
  expect 'ҫ'.u do 'Ҫ'.u.downcase end
  expect 'Ҫ'.u do 'ҫ'.u.upcase end
  expect 'ҭ'.u do 'Ҭ'.u.downcase end
  expect 'Ҭ'.u do 'ҭ'.u.upcase end
  expect 'ү'.u do 'Ү'.u.downcase end
  expect 'Ү'.u do 'ү'.u.upcase end
  expect 'ұ'.u do 'Ұ'.u.downcase end
  expect 'Ұ'.u do 'ұ'.u.upcase end
  expect 'ҳ'.u do 'Ҳ'.u.downcase end
  expect 'Ҳ'.u do 'ҳ'.u.upcase end
  expect 'ҵ'.u do 'Ҵ'.u.downcase end
  expect 'Ҵ'.u do 'ҵ'.u.upcase end
  expect 'ҷ'.u do 'Ҷ'.u.downcase end
  expect 'Ҷ'.u do 'ҷ'.u.upcase end
  expect 'ҹ'.u do 'Ҹ'.u.downcase end
  expect 'Ҹ'.u do 'ҹ'.u.upcase end
  expect 'һ'.u do 'Һ'.u.downcase end
  expect 'Һ'.u do 'һ'.u.upcase end
  expect 'ҽ'.u do 'Ҽ'.u.downcase end
  expect 'Ҽ'.u do 'ҽ'.u.upcase end
  expect 'ҿ'.u do 'Ҿ'.u.downcase end
  expect 'Ҿ'.u do 'ҿ'.u.upcase end
  expect 'ӏ'.u do 'Ӏ'.u.downcase end
  expect 'ӂ'.u do 'Ӂ'.u.downcase end
  expect 'Ӂ'.u do 'ӂ'.u.upcase end
  expect 'ӄ'.u do 'Ӄ'.u.downcase end
  expect 'Ӄ'.u do 'ӄ'.u.upcase end
  expect 'ӆ'.u do 'Ӆ'.u.downcase end
  expect 'Ӆ'.u do 'ӆ'.u.upcase end
  expect 'ӈ'.u do 'Ӈ'.u.downcase end
  expect 'Ӈ'.u do 'ӈ'.u.upcase end
  expect 'ӊ'.u do 'Ӊ'.u.downcase end
  expect 'Ӊ'.u do 'ӊ'.u.upcase end
  expect 'ӌ'.u do 'Ӌ'.u.downcase end
  expect 'Ӌ'.u do 'ӌ'.u.upcase end
  expect 'ӎ'.u do 'Ӎ'.u.downcase end
  expect 'Ӎ'.u do 'ӎ'.u.upcase end
  expect 'Ӏ'.u do 'ӏ'.u.upcase end
  expect 'ӑ'.u do 'Ӑ'.u.downcase end
  expect 'Ӑ'.u do 'ӑ'.u.upcase end
  expect 'ӓ'.u do 'Ӓ'.u.downcase end
  expect 'Ӓ'.u do 'ӓ'.u.upcase end
  expect 'ӕ'.u do 'Ӕ'.u.downcase end
  expect 'Ӕ'.u do 'ӕ'.u.upcase end
  expect 'ӗ'.u do 'Ӗ'.u.downcase end
  expect 'Ӗ'.u do 'ӗ'.u.upcase end
  expect 'ә'.u do 'Ә'.u.downcase end
  expect 'Ә'.u do 'ә'.u.upcase end
  expect 'ӛ'.u do 'Ӛ'.u.downcase end
  expect 'Ӛ'.u do 'ӛ'.u.upcase end
  expect 'ӝ'.u do 'Ӝ'.u.downcase end
  expect 'Ӝ'.u do 'ӝ'.u.upcase end
  expect 'ӟ'.u do 'Ӟ'.u.downcase end
  expect 'Ӟ'.u do 'ӟ'.u.upcase end
  expect 'ӡ'.u do 'Ӡ'.u.downcase end
  expect 'Ӡ'.u do 'ӡ'.u.upcase end
  expect 'ӣ'.u do 'Ӣ'.u.downcase end
  expect 'Ӣ'.u do 'ӣ'.u.upcase end
  expect 'ӥ'.u do 'Ӥ'.u.downcase end
  expect 'Ӥ'.u do 'ӥ'.u.upcase end
  expect 'ӧ'.u do 'Ӧ'.u.downcase end
  expect 'Ӧ'.u do 'ӧ'.u.upcase end
  expect 'ө'.u do 'Ө'.u.downcase end
  expect 'Ө'.u do 'ө'.u.upcase end
  expect 'ӫ'.u do 'Ӫ'.u.downcase end
  expect 'Ӫ'.u do 'ӫ'.u.upcase end
  expect 'ӭ'.u do 'Ӭ'.u.downcase end
  expect 'Ӭ'.u do 'ӭ'.u.upcase end
  expect 'ӯ'.u do 'Ӯ'.u.downcase end
  expect 'Ӯ'.u do 'ӯ'.u.upcase end
  expect 'ӱ'.u do 'Ӱ'.u.downcase end
  expect 'Ӱ'.u do 'ӱ'.u.upcase end
  expect 'ӳ'.u do 'Ӳ'.u.downcase end
  expect 'Ӳ'.u do 'ӳ'.u.upcase end
  expect 'ӵ'.u do 'Ӵ'.u.downcase end
  expect 'Ӵ'.u do 'ӵ'.u.upcase end
  expect 'ӷ'.u do 'Ӷ'.u.downcase end
  expect 'Ӷ'.u do 'ӷ'.u.upcase end
  expect 'ӹ'.u do 'Ӹ'.u.downcase end
  expect 'Ӹ'.u do 'ӹ'.u.upcase end
  expect 'ӻ'.u do 'Ӻ'.u.downcase end
  expect 'Ӻ'.u do 'ӻ'.u.upcase end
  expect 'ӽ'.u do 'Ӽ'.u.downcase end
  expect 'Ӽ'.u do 'ӽ'.u.upcase end
  expect 'ӿ'.u do 'Ӿ'.u.downcase end
  expect 'Ӿ'.u do 'ӿ'.u.upcase end
  expect 'ԁ'.u do 'Ԁ'.u.downcase end
  expect 'Ԁ'.u do 'ԁ'.u.upcase end
  expect 'ԃ'.u do 'Ԃ'.u.downcase end
  expect 'Ԃ'.u do 'ԃ'.u.upcase end
  expect 'ԅ'.u do 'Ԅ'.u.downcase end
  expect 'Ԅ'.u do 'ԅ'.u.upcase end
  expect 'ԇ'.u do 'Ԇ'.u.downcase end
  expect 'Ԇ'.u do 'ԇ'.u.upcase end
  expect 'ԉ'.u do 'Ԉ'.u.downcase end
  expect 'Ԉ'.u do 'ԉ'.u.upcase end
  expect 'ԋ'.u do 'Ԋ'.u.downcase end
  expect 'Ԋ'.u do 'ԋ'.u.upcase end
  expect 'ԍ'.u do 'Ԍ'.u.downcase end
  expect 'Ԍ'.u do 'ԍ'.u.upcase end
  expect 'ԏ'.u do 'Ԏ'.u.downcase end
  expect 'Ԏ'.u do 'ԏ'.u.upcase end
  expect 'ԑ'.u do 'Ԑ'.u.downcase end
  expect 'Ԑ'.u do 'ԑ'.u.upcase end
  expect 'ԓ'.u do 'Ԓ'.u.downcase end
  expect 'Ԓ'.u do 'ԓ'.u.upcase end
  expect 'ա'.u do 'Ա'.u.downcase end
  expect 'բ'.u do 'Բ'.u.downcase end
  expect 'գ'.u do 'Գ'.u.downcase end
  expect 'դ'.u do 'Դ'.u.downcase end
  expect 'ե'.u do 'Ե'.u.downcase end
  expect 'զ'.u do 'Զ'.u.downcase end
  expect 'է'.u do 'Է'.u.downcase end
  expect 'ը'.u do 'Ը'.u.downcase end
  expect 'թ'.u do 'Թ'.u.downcase end
  expect 'ժ'.u do 'Ժ'.u.downcase end
  expect 'ի'.u do 'Ի'.u.downcase end
  expect 'լ'.u do 'Լ'.u.downcase end
  expect 'խ'.u do 'Խ'.u.downcase end
  expect 'ծ'.u do 'Ծ'.u.downcase end
  expect 'կ'.u do 'Կ'.u.downcase end
  expect 'հ'.u do 'Հ'.u.downcase end
  expect 'ձ'.u do 'Ձ'.u.downcase end
  expect 'ղ'.u do 'Ղ'.u.downcase end
  expect 'ճ'.u do 'Ճ'.u.downcase end
  expect 'մ'.u do 'Մ'.u.downcase end
  expect 'յ'.u do 'Յ'.u.downcase end
  expect 'ն'.u do 'Ն'.u.downcase end
  expect 'շ'.u do 'Շ'.u.downcase end
  expect 'ո'.u do 'Ո'.u.downcase end
  expect 'չ'.u do 'Չ'.u.downcase end
  expect 'պ'.u do 'Պ'.u.downcase end
  expect 'ջ'.u do 'Ջ'.u.downcase end
  expect 'ռ'.u do 'Ռ'.u.downcase end
  expect 'ս'.u do 'Ս'.u.downcase end
  expect 'վ'.u do 'Վ'.u.downcase end
  expect 'տ'.u do 'Տ'.u.downcase end
  expect 'ր'.u do 'Ր'.u.downcase end
  expect 'ց'.u do 'Ց'.u.downcase end
  expect 'ւ'.u do 'Ւ'.u.downcase end
  expect 'փ'.u do 'Փ'.u.downcase end
  expect 'ք'.u do 'Ք'.u.downcase end
  expect 'օ'.u do 'Օ'.u.downcase end
  expect 'ֆ'.u do 'Ֆ'.u.downcase end
  expect 'Ա'.u do 'ա'.u.upcase end
  expect 'Բ'.u do 'բ'.u.upcase end
  expect 'Գ'.u do 'գ'.u.upcase end
  expect 'Դ'.u do 'դ'.u.upcase end
  expect 'Ե'.u do 'ե'.u.upcase end
  expect 'Զ'.u do 'զ'.u.upcase end
  expect 'Է'.u do 'է'.u.upcase end
  expect 'Ը'.u do 'ը'.u.upcase end
  expect 'Թ'.u do 'թ'.u.upcase end
  expect 'Ժ'.u do 'ժ'.u.upcase end
  expect 'Ի'.u do 'ի'.u.upcase end
  expect 'Լ'.u do 'լ'.u.upcase end
  expect 'Խ'.u do 'խ'.u.upcase end
  expect 'Ծ'.u do 'ծ'.u.upcase end
  expect 'Կ'.u do 'կ'.u.upcase end
  expect 'Հ'.u do 'հ'.u.upcase end
  expect 'Ձ'.u do 'ձ'.u.upcase end
  expect 'Ղ'.u do 'ղ'.u.upcase end
  expect 'Ճ'.u do 'ճ'.u.upcase end
  expect 'Մ'.u do 'մ'.u.upcase end
  expect 'Յ'.u do 'յ'.u.upcase end
  expect 'Ն'.u do 'ն'.u.upcase end
  expect 'Շ'.u do 'շ'.u.upcase end
  expect 'Ո'.u do 'ո'.u.upcase end
  expect 'Չ'.u do 'չ'.u.upcase end
  expect 'Պ'.u do 'պ'.u.upcase end
  expect 'Ջ'.u do 'ջ'.u.upcase end
  expect 'Ռ'.u do 'ռ'.u.upcase end
  expect 'Ս'.u do 'ս'.u.upcase end
  expect 'Վ'.u do 'վ'.u.upcase end
  expect 'Տ'.u do 'տ'.u.upcase end
  expect 'Ր'.u do 'ր'.u.upcase end
  expect 'Ց'.u do 'ց'.u.upcase end
  expect 'Ւ'.u do 'ւ'.u.upcase end
  expect 'Փ'.u do 'փ'.u.upcase end
  expect 'Ք'.u do 'ք'.u.upcase end
  expect 'Օ'.u do 'օ'.u.upcase end
  expect 'Ֆ'.u do 'ֆ'.u.upcase end
  expect 'ԵՒ'.u do 'և'.u.upcase end
  expect 'ⴀ'.u do 'Ⴀ'.u.downcase end
  expect 'ⴁ'.u do 'Ⴁ'.u.downcase end
  expect 'ⴂ'.u do 'Ⴂ'.u.downcase end
  expect 'ⴃ'.u do 'Ⴃ'.u.downcase end
  expect 'ⴄ'.u do 'Ⴄ'.u.downcase end
  expect 'ⴅ'.u do 'Ⴅ'.u.downcase end
  expect 'ⴆ'.u do 'Ⴆ'.u.downcase end
  expect 'ⴇ'.u do 'Ⴇ'.u.downcase end
  expect 'ⴈ'.u do 'Ⴈ'.u.downcase end
  expect 'ⴉ'.u do 'Ⴉ'.u.downcase end
  expect 'ⴊ'.u do 'Ⴊ'.u.downcase end
  expect 'ⴋ'.u do 'Ⴋ'.u.downcase end
  expect 'ⴌ'.u do 'Ⴌ'.u.downcase end
  expect 'ⴍ'.u do 'Ⴍ'.u.downcase end
  expect 'ⴎ'.u do 'Ⴎ'.u.downcase end
  expect 'ⴏ'.u do 'Ⴏ'.u.downcase end
  expect 'ⴐ'.u do 'Ⴐ'.u.downcase end
  expect 'ⴑ'.u do 'Ⴑ'.u.downcase end
  expect 'ⴒ'.u do 'Ⴒ'.u.downcase end
  expect 'ⴓ'.u do 'Ⴓ'.u.downcase end
  expect 'ⴔ'.u do 'Ⴔ'.u.downcase end
  expect 'ⴕ'.u do 'Ⴕ'.u.downcase end
  expect 'ⴖ'.u do 'Ⴖ'.u.downcase end
  expect 'ⴗ'.u do 'Ⴗ'.u.downcase end
  expect 'ⴘ'.u do 'Ⴘ'.u.downcase end
  expect 'ⴙ'.u do 'Ⴙ'.u.downcase end
  expect 'ⴚ'.u do 'Ⴚ'.u.downcase end
  expect 'ⴛ'.u do 'Ⴛ'.u.downcase end
  expect 'ⴜ'.u do 'Ⴜ'.u.downcase end
  expect 'ⴝ'.u do 'Ⴝ'.u.downcase end
  expect 'ⴞ'.u do 'Ⴞ'.u.downcase end
  expect 'ⴟ'.u do 'Ⴟ'.u.downcase end
  expect 'ⴠ'.u do 'Ⴠ'.u.downcase end
  expect 'ⴡ'.u do 'Ⴡ'.u.downcase end
  expect 'ⴢ'.u do 'Ⴢ'.u.downcase end
  expect 'ⴣ'.u do 'Ⴣ'.u.downcase end
  expect 'ⴤ'.u do 'Ⴤ'.u.downcase end
  expect 'ⴥ'.u do 'Ⴥ'.u.downcase end
  expect 'Ᵽ'.u do 'ᵽ'.u.upcase end
  expect 'ḁ'.u do 'Ḁ'.u.downcase end
  expect 'Ḁ'.u do 'ḁ'.u.upcase end
  expect 'ḃ'.u do 'Ḃ'.u.downcase end
  expect 'Ḃ'.u do 'ḃ'.u.upcase end
  expect 'ḅ'.u do 'Ḅ'.u.downcase end
  expect 'Ḅ'.u do 'ḅ'.u.upcase end
  expect 'ḇ'.u do 'Ḇ'.u.downcase end
  expect 'Ḇ'.u do 'ḇ'.u.upcase end
  expect 'ḉ'.u do 'Ḉ'.u.downcase end
  expect 'Ḉ'.u do 'ḉ'.u.upcase end
  expect 'ḋ'.u do 'Ḋ'.u.downcase end
  expect 'Ḋ'.u do 'ḋ'.u.upcase end
  expect 'ḍ'.u do 'Ḍ'.u.downcase end
  expect 'Ḍ'.u do 'ḍ'.u.upcase end
  expect 'ḏ'.u do 'Ḏ'.u.downcase end
  expect 'Ḏ'.u do 'ḏ'.u.upcase end
  expect 'ḑ'.u do 'Ḑ'.u.downcase end
  expect 'Ḑ'.u do 'ḑ'.u.upcase end
  expect 'ḓ'.u do 'Ḓ'.u.downcase end
  expect 'Ḓ'.u do 'ḓ'.u.upcase end
  expect 'ḕ'.u do 'Ḕ'.u.downcase end
  expect 'Ḕ'.u do 'ḕ'.u.upcase end
  expect 'ḗ'.u do 'Ḗ'.u.downcase end
  expect 'Ḗ'.u do 'ḗ'.u.upcase end
  expect 'ḙ'.u do 'Ḙ'.u.downcase end
  expect 'Ḙ'.u do 'ḙ'.u.upcase end
  expect 'ḛ'.u do 'Ḛ'.u.downcase end
  expect 'Ḛ'.u do 'ḛ'.u.upcase end
  expect 'ḝ'.u do 'Ḝ'.u.downcase end
  expect 'Ḝ'.u do 'ḝ'.u.upcase end
  expect 'ḟ'.u do 'Ḟ'.u.downcase end
  expect 'Ḟ'.u do 'ḟ'.u.upcase end
  expect 'ḡ'.u do 'Ḡ'.u.downcase end
  expect 'Ḡ'.u do 'ḡ'.u.upcase end
  expect 'ḣ'.u do 'Ḣ'.u.downcase end
  expect 'Ḣ'.u do 'ḣ'.u.upcase end
  expect 'ḥ'.u do 'Ḥ'.u.downcase end
  expect 'Ḥ'.u do 'ḥ'.u.upcase end
  expect 'ḧ'.u do 'Ḧ'.u.downcase end
  expect 'Ḧ'.u do 'ḧ'.u.upcase end
  expect 'ḩ'.u do 'Ḩ'.u.downcase end
  expect 'Ḩ'.u do 'ḩ'.u.upcase end
  expect 'ḫ'.u do 'Ḫ'.u.downcase end
  expect 'Ḫ'.u do 'ḫ'.u.upcase end
  expect 'ḭ'.u do 'Ḭ'.u.downcase end
  expect 'Ḭ'.u do 'ḭ'.u.upcase end
  expect 'ḯ'.u do 'Ḯ'.u.downcase end
  expect 'Ḯ'.u do 'ḯ'.u.upcase end
  expect 'ḱ'.u do 'Ḱ'.u.downcase end
  expect 'Ḱ'.u do 'ḱ'.u.upcase end
  expect 'ḳ'.u do 'Ḳ'.u.downcase end
  expect 'Ḳ'.u do 'ḳ'.u.upcase end
  expect 'ḵ'.u do 'Ḵ'.u.downcase end
  expect 'Ḵ'.u do 'ḵ'.u.upcase end
  expect 'ḷ'.u do 'Ḷ'.u.downcase end
  expect 'Ḷ'.u do 'ḷ'.u.upcase end
  expect 'ḹ'.u do 'Ḹ'.u.downcase end
  expect 'Ḹ'.u do 'ḹ'.u.upcase end
  expect 'ḻ'.u do 'Ḻ'.u.downcase end
  expect 'Ḻ'.u do 'ḻ'.u.upcase end
  expect 'ḽ'.u do 'Ḽ'.u.downcase end
  expect 'Ḽ'.u do 'ḽ'.u.upcase end
  expect 'ḿ'.u do 'Ḿ'.u.downcase end
  expect 'Ḿ'.u do 'ḿ'.u.upcase end
  expect 'ṁ'.u do 'Ṁ'.u.downcase end
  expect 'Ṁ'.u do 'ṁ'.u.upcase end
  expect 'ṃ'.u do 'Ṃ'.u.downcase end
  expect 'Ṃ'.u do 'ṃ'.u.upcase end
  expect 'ṅ'.u do 'Ṅ'.u.downcase end
  expect 'Ṅ'.u do 'ṅ'.u.upcase end
  expect 'ṇ'.u do 'Ṇ'.u.downcase end
  expect 'Ṇ'.u do 'ṇ'.u.upcase end
  expect 'ṉ'.u do 'Ṉ'.u.downcase end
  expect 'Ṉ'.u do 'ṉ'.u.upcase end
  expect 'ṋ'.u do 'Ṋ'.u.downcase end
  expect 'Ṋ'.u do 'ṋ'.u.upcase end
  expect 'ṍ'.u do 'Ṍ'.u.downcase end
  expect 'Ṍ'.u do 'ṍ'.u.upcase end
  expect 'ṏ'.u do 'Ṏ'.u.downcase end
  expect 'Ṏ'.u do 'ṏ'.u.upcase end
  expect 'ṑ'.u do 'Ṑ'.u.downcase end
  expect 'Ṑ'.u do 'ṑ'.u.upcase end
  expect 'ṓ'.u do 'Ṓ'.u.downcase end
  expect 'Ṓ'.u do 'ṓ'.u.upcase end
  expect 'ṕ'.u do 'Ṕ'.u.downcase end
  expect 'Ṕ'.u do 'ṕ'.u.upcase end
  expect 'ṗ'.u do 'Ṗ'.u.downcase end
  expect 'Ṗ'.u do 'ṗ'.u.upcase end
  expect 'ṙ'.u do 'Ṙ'.u.downcase end
  expect 'Ṙ'.u do 'ṙ'.u.upcase end
  expect 'ṛ'.u do 'Ṛ'.u.downcase end
  expect 'Ṛ'.u do 'ṛ'.u.upcase end
  expect 'ṝ'.u do 'Ṝ'.u.downcase end
  expect 'Ṝ'.u do 'ṝ'.u.upcase end
  expect 'ṟ'.u do 'Ṟ'.u.downcase end
  expect 'Ṟ'.u do 'ṟ'.u.upcase end
  expect 'ṡ'.u do 'Ṡ'.u.downcase end
  expect 'Ṡ'.u do 'ṡ'.u.upcase end
  expect 'ṣ'.u do 'Ṣ'.u.downcase end
  expect 'Ṣ'.u do 'ṣ'.u.upcase end
  expect 'ṥ'.u do 'Ṥ'.u.downcase end
  expect 'Ṥ'.u do 'ṥ'.u.upcase end
  expect 'ṧ'.u do 'Ṧ'.u.downcase end
  expect 'Ṧ'.u do 'ṧ'.u.upcase end
  expect 'ṩ'.u do 'Ṩ'.u.downcase end
  expect 'Ṩ'.u do 'ṩ'.u.upcase end
  expect 'ṫ'.u do 'Ṫ'.u.downcase end
  expect 'Ṫ'.u do 'ṫ'.u.upcase end
  expect 'ṭ'.u do 'Ṭ'.u.downcase end
  expect 'Ṭ'.u do 'ṭ'.u.upcase end
  expect 'ṯ'.u do 'Ṯ'.u.downcase end
  expect 'Ṯ'.u do 'ṯ'.u.upcase end
  expect 'ṱ'.u do 'Ṱ'.u.downcase end
  expect 'Ṱ'.u do 'ṱ'.u.upcase end
  expect 'ṳ'.u do 'Ṳ'.u.downcase end
  expect 'Ṳ'.u do 'ṳ'.u.upcase end
  expect 'ṵ'.u do 'Ṵ'.u.downcase end
  expect 'Ṵ'.u do 'ṵ'.u.upcase end
  expect 'ṷ'.u do 'Ṷ'.u.downcase end
  expect 'Ṷ'.u do 'ṷ'.u.upcase end
  expect 'ṹ'.u do 'Ṹ'.u.downcase end
  expect 'Ṹ'.u do 'ṹ'.u.upcase end
  expect 'ṻ'.u do 'Ṻ'.u.downcase end
  expect 'Ṻ'.u do 'ṻ'.u.upcase end
  expect 'ṽ'.u do 'Ṽ'.u.downcase end
  expect 'Ṽ'.u do 'ṽ'.u.upcase end
  expect 'ṿ'.u do 'Ṿ'.u.downcase end
  expect 'Ṿ'.u do 'ṿ'.u.upcase end
  expect 'ẁ'.u do 'Ẁ'.u.downcase end
  expect 'Ẁ'.u do 'ẁ'.u.upcase end
  expect 'ẃ'.u do 'Ẃ'.u.downcase end
  expect 'Ẃ'.u do 'ẃ'.u.upcase end
  expect 'ẅ'.u do 'Ẅ'.u.downcase end
  expect 'Ẅ'.u do 'ẅ'.u.upcase end
  expect 'ẇ'.u do 'Ẇ'.u.downcase end
  expect 'Ẇ'.u do 'ẇ'.u.upcase end
  expect 'ẉ'.u do 'Ẉ'.u.downcase end
  expect 'Ẉ'.u do 'ẉ'.u.upcase end
  expect 'ẋ'.u do 'Ẋ'.u.downcase end
  expect 'Ẋ'.u do 'ẋ'.u.upcase end
  expect 'ẍ'.u do 'Ẍ'.u.downcase end
  expect 'Ẍ'.u do 'ẍ'.u.upcase end
  expect 'ẏ'.u do 'Ẏ'.u.downcase end
  expect 'Ẏ'.u do 'ẏ'.u.upcase end
  expect 'ẑ'.u do 'Ẑ'.u.downcase end
  expect 'Ẑ'.u do 'ẑ'.u.upcase end
  expect 'ẓ'.u do 'Ẓ'.u.downcase end
  expect 'Ẓ'.u do 'ẓ'.u.upcase end
  expect 'ẕ'.u do 'Ẕ'.u.downcase end
  expect 'Ẕ'.u do 'ẕ'.u.upcase end
  expect 'H̱'.u do 'ẖ'.u.upcase end
  expect 'T̈'.u do 'ẗ'.u.upcase end
  expect 'W̊'.u do 'ẘ'.u.upcase end
  expect 'Y̊'.u do 'ẙ'.u.upcase end
  expect 'Aʾ'.u do 'ẚ'.u.upcase end
  expect 'Ṡ'.u do 'ẛ'.u.upcase end
  expect 'ạ'.u do 'Ạ'.u.downcase end
  expect 'Ạ'.u do 'ạ'.u.upcase end
  expect 'ả'.u do 'Ả'.u.downcase end
  expect 'Ả'.u do 'ả'.u.upcase end
  expect 'ấ'.u do 'Ấ'.u.downcase end
  expect 'Ấ'.u do 'ấ'.u.upcase end
  expect 'ầ'.u do 'Ầ'.u.downcase end
  expect 'Ầ'.u do 'ầ'.u.upcase end
  expect 'ẩ'.u do 'Ẩ'.u.downcase end
  expect 'Ẩ'.u do 'ẩ'.u.upcase end
  expect 'ẫ'.u do 'Ẫ'.u.downcase end
  expect 'Ẫ'.u do 'ẫ'.u.upcase end
  expect 'ậ'.u do 'Ậ'.u.downcase end
  expect 'Ậ'.u do 'ậ'.u.upcase end
  expect 'ắ'.u do 'Ắ'.u.downcase end
  expect 'Ắ'.u do 'ắ'.u.upcase end
  expect 'ằ'.u do 'Ằ'.u.downcase end
  expect 'Ằ'.u do 'ằ'.u.upcase end
  expect 'ẳ'.u do 'Ẳ'.u.downcase end
  expect 'Ẳ'.u do 'ẳ'.u.upcase end
  expect 'ẵ'.u do 'Ẵ'.u.downcase end
  expect 'Ẵ'.u do 'ẵ'.u.upcase end
  expect 'ặ'.u do 'Ặ'.u.downcase end
  expect 'Ặ'.u do 'ặ'.u.upcase end
  expect 'ẹ'.u do 'Ẹ'.u.downcase end
  expect 'Ẹ'.u do 'ẹ'.u.upcase end
  expect 'ẻ'.u do 'Ẻ'.u.downcase end
  expect 'Ẻ'.u do 'ẻ'.u.upcase end
  expect 'ẽ'.u do 'Ẽ'.u.downcase end
  expect 'Ẽ'.u do 'ẽ'.u.upcase end
  expect 'ế'.u do 'Ế'.u.downcase end
  expect 'Ế'.u do 'ế'.u.upcase end
  expect 'ề'.u do 'Ề'.u.downcase end
  expect 'Ề'.u do 'ề'.u.upcase end
  expect 'ể'.u do 'Ể'.u.downcase end
  expect 'Ể'.u do 'ể'.u.upcase end
  expect 'ễ'.u do 'Ễ'.u.downcase end
  expect 'Ễ'.u do 'ễ'.u.upcase end
  expect 'ệ'.u do 'Ệ'.u.downcase end
  expect 'Ệ'.u do 'ệ'.u.upcase end
  expect 'ỉ'.u do 'Ỉ'.u.downcase end
  expect 'Ỉ'.u do 'ỉ'.u.upcase end
  expect 'ị'.u do 'Ị'.u.downcase end
  expect 'Ị'.u do 'ị'.u.upcase end
  expect 'ọ'.u do 'Ọ'.u.downcase end
  expect 'Ọ'.u do 'ọ'.u.upcase end
  expect 'ỏ'.u do 'Ỏ'.u.downcase end
  expect 'Ỏ'.u do 'ỏ'.u.upcase end
  expect 'ố'.u do 'Ố'.u.downcase end
  expect 'Ố'.u do 'ố'.u.upcase end
  expect 'ồ'.u do 'Ồ'.u.downcase end
  expect 'Ồ'.u do 'ồ'.u.upcase end
  expect 'ổ'.u do 'Ổ'.u.downcase end
  expect 'Ổ'.u do 'ổ'.u.upcase end
  expect 'ỗ'.u do 'Ỗ'.u.downcase end
  expect 'Ỗ'.u do 'ỗ'.u.upcase end
  expect 'ộ'.u do 'Ộ'.u.downcase end
  expect 'Ộ'.u do 'ộ'.u.upcase end
  expect 'ớ'.u do 'Ớ'.u.downcase end
  expect 'Ớ'.u do 'ớ'.u.upcase end
  expect 'ờ'.u do 'Ờ'.u.downcase end
  expect 'Ờ'.u do 'ờ'.u.upcase end
  expect 'ở'.u do 'Ở'.u.downcase end
  expect 'Ở'.u do 'ở'.u.upcase end
  expect 'ỡ'.u do 'Ỡ'.u.downcase end
  expect 'Ỡ'.u do 'ỡ'.u.upcase end
  expect 'ợ'.u do 'Ợ'.u.downcase end
  expect 'Ợ'.u do 'ợ'.u.upcase end
  expect 'ụ'.u do 'Ụ'.u.downcase end
  expect 'Ụ'.u do 'ụ'.u.upcase end
  expect 'ủ'.u do 'Ủ'.u.downcase end
  expect 'Ủ'.u do 'ủ'.u.upcase end
  expect 'ứ'.u do 'Ứ'.u.downcase end
  expect 'Ứ'.u do 'ứ'.u.upcase end
  expect 'ừ'.u do 'Ừ'.u.downcase end
  expect 'Ừ'.u do 'ừ'.u.upcase end
  expect 'ử'.u do 'Ử'.u.downcase end
  expect 'Ử'.u do 'ử'.u.upcase end
  expect 'ữ'.u do 'Ữ'.u.downcase end
  expect 'Ữ'.u do 'ữ'.u.upcase end
  expect 'ự'.u do 'Ự'.u.downcase end
  expect 'Ự'.u do 'ự'.u.upcase end
  expect 'ỳ'.u do 'Ỳ'.u.downcase end
  expect 'Ỳ'.u do 'ỳ'.u.upcase end
  expect 'ỵ'.u do 'Ỵ'.u.downcase end
  expect 'Ỵ'.u do 'ỵ'.u.upcase end
  expect 'ỷ'.u do 'Ỷ'.u.downcase end
  expect 'Ỷ'.u do 'ỷ'.u.upcase end
  expect 'ỹ'.u do 'Ỹ'.u.downcase end
  expect 'Ỹ'.u do 'ỹ'.u.upcase end
  expect 'Ἀ'.u do 'ἀ'.u.upcase end
  expect 'Ἁ'.u do 'ἁ'.u.upcase end
  expect 'Ἂ'.u do 'ἂ'.u.upcase end
  expect 'Ἃ'.u do 'ἃ'.u.upcase end
  expect 'Ἄ'.u do 'ἄ'.u.upcase end
  expect 'Ἅ'.u do 'ἅ'.u.upcase end
  expect 'Ἆ'.u do 'ἆ'.u.upcase end
  expect 'Ἇ'.u do 'ἇ'.u.upcase end
  expect 'ἀ'.u do 'Ἀ'.u.downcase end
  expect 'ἁ'.u do 'Ἁ'.u.downcase end
  expect 'ἂ'.u do 'Ἂ'.u.downcase end
  expect 'ἃ'.u do 'Ἃ'.u.downcase end
  expect 'ἄ'.u do 'Ἄ'.u.downcase end
  expect 'ἅ'.u do 'Ἅ'.u.downcase end
  expect 'ἆ'.u do 'Ἆ'.u.downcase end
  expect 'ἇ'.u do 'Ἇ'.u.downcase end
  expect 'Ἐ'.u do 'ἐ'.u.upcase end
  expect 'Ἑ'.u do 'ἑ'.u.upcase end
  expect 'Ἒ'.u do 'ἒ'.u.upcase end
  expect 'Ἓ'.u do 'ἓ'.u.upcase end
  expect 'Ἔ'.u do 'ἔ'.u.upcase end
  expect 'Ἕ'.u do 'ἕ'.u.upcase end
  expect 'ἐ'.u do 'Ἐ'.u.downcase end
  expect 'ἑ'.u do 'Ἑ'.u.downcase end
  expect 'ἒ'.u do 'Ἒ'.u.downcase end
  expect 'ἓ'.u do 'Ἓ'.u.downcase end
  expect 'ἔ'.u do 'Ἔ'.u.downcase end
  expect 'ἕ'.u do 'Ἕ'.u.downcase end
  expect 'Ἠ'.u do 'ἠ'.u.upcase end
  expect 'Ἡ'.u do 'ἡ'.u.upcase end
  expect 'Ἢ'.u do 'ἢ'.u.upcase end
  expect 'Ἣ'.u do 'ἣ'.u.upcase end
  expect 'Ἤ'.u do 'ἤ'.u.upcase end
  expect 'Ἥ'.u do 'ἥ'.u.upcase end
  expect 'Ἦ'.u do 'ἦ'.u.upcase end
  expect 'Ἧ'.u do 'ἧ'.u.upcase end
  expect 'ἠ'.u do 'Ἠ'.u.downcase end
  expect 'ἡ'.u do 'Ἡ'.u.downcase end
  expect 'ἢ'.u do 'Ἢ'.u.downcase end
  expect 'ἣ'.u do 'Ἣ'.u.downcase end
  expect 'ἤ'.u do 'Ἤ'.u.downcase end
  expect 'ἥ'.u do 'Ἥ'.u.downcase end
  expect 'ἦ'.u do 'Ἦ'.u.downcase end
  expect 'ἧ'.u do 'Ἧ'.u.downcase end
  expect 'Ἰ'.u do 'ἰ'.u.upcase end
  expect 'Ἱ'.u do 'ἱ'.u.upcase end
  expect 'Ἲ'.u do 'ἲ'.u.upcase end
  expect 'Ἳ'.u do 'ἳ'.u.upcase end
  expect 'Ἴ'.u do 'ἴ'.u.upcase end
  expect 'Ἵ'.u do 'ἵ'.u.upcase end
  expect 'Ἶ'.u do 'ἶ'.u.upcase end
  expect 'Ἷ'.u do 'ἷ'.u.upcase end
  expect 'ἰ'.u do 'Ἰ'.u.downcase end
  expect 'ἱ'.u do 'Ἱ'.u.downcase end
  expect 'ἲ'.u do 'Ἲ'.u.downcase end
  expect 'ἳ'.u do 'Ἳ'.u.downcase end
  expect 'ἴ'.u do 'Ἴ'.u.downcase end
  expect 'ἵ'.u do 'Ἵ'.u.downcase end
  expect 'ἶ'.u do 'Ἶ'.u.downcase end
  expect 'ἷ'.u do 'Ἷ'.u.downcase end
  expect 'Ὀ'.u do 'ὀ'.u.upcase end
  expect 'Ὁ'.u do 'ὁ'.u.upcase end
  expect 'Ὂ'.u do 'ὂ'.u.upcase end
  expect 'Ὃ'.u do 'ὃ'.u.upcase end
  expect 'Ὄ'.u do 'ὄ'.u.upcase end
  expect 'Ὅ'.u do 'ὅ'.u.upcase end
  expect 'ὀ'.u do 'Ὀ'.u.downcase end
  expect 'ὁ'.u do 'Ὁ'.u.downcase end
  expect 'ὂ'.u do 'Ὂ'.u.downcase end
  expect 'ὃ'.u do 'Ὃ'.u.downcase end
  expect 'ὄ'.u do 'Ὄ'.u.downcase end
  expect 'ὅ'.u do 'Ὅ'.u.downcase end
  expect 'Υ̓'.u do 'ὐ'.u.upcase end
  expect 'Ὑ'.u do 'ὑ'.u.upcase end
  expect 'Υ̓̀'.u do 'ὒ'.u.upcase end
  expect 'Ὓ'.u do 'ὓ'.u.upcase end
  expect 'Υ̓́'.u do 'ὔ'.u.upcase end
  expect 'Ὕ'.u do 'ὕ'.u.upcase end
  expect 'Υ̓͂'.u do 'ὖ'.u.upcase end
  expect 'Ὗ'.u do 'ὗ'.u.upcase end
  expect 'ὑ'.u do 'Ὑ'.u.downcase end
  expect 'ὓ'.u do 'Ὓ'.u.downcase end
  expect 'ὕ'.u do 'Ὕ'.u.downcase end
  expect 'ὗ'.u do 'Ὗ'.u.downcase end
  expect 'Ὠ'.u do 'ὠ'.u.upcase end
  expect 'Ὡ'.u do 'ὡ'.u.upcase end
  expect 'Ὢ'.u do 'ὢ'.u.upcase end
  expect 'Ὣ'.u do 'ὣ'.u.upcase end
  expect 'Ὤ'.u do 'ὤ'.u.upcase end
  expect 'Ὥ'.u do 'ὥ'.u.upcase end
  expect 'Ὦ'.u do 'ὦ'.u.upcase end
  expect 'Ὧ'.u do 'ὧ'.u.upcase end
  expect 'ὠ'.u do 'Ὠ'.u.downcase end
  expect 'ὡ'.u do 'Ὡ'.u.downcase end
  expect 'ὢ'.u do 'Ὢ'.u.downcase end
  expect 'ὣ'.u do 'Ὣ'.u.downcase end
  expect 'ὤ'.u do 'Ὤ'.u.downcase end
  expect 'ὥ'.u do 'Ὥ'.u.downcase end
  expect 'ὦ'.u do 'Ὦ'.u.downcase end
  expect 'ὧ'.u do 'Ὧ'.u.downcase end
  expect 'Ὰ'.u do 'ὰ'.u.upcase end
  expect 'Ά'.u do 'ά'.u.upcase end
  expect 'Ὲ'.u do 'ὲ'.u.upcase end
  expect 'Έ'.u do 'έ'.u.upcase end
  expect 'Ὴ'.u do 'ὴ'.u.upcase end
  expect 'Ή'.u do 'ή'.u.upcase end
  expect 'Ὶ'.u do 'ὶ'.u.upcase end
  expect 'Ί'.u do 'ί'.u.upcase end
  expect 'Ὸ'.u do 'ὸ'.u.upcase end
  expect 'Ό'.u do 'ό'.u.upcase end
  expect 'Ὺ'.u do 'ὺ'.u.upcase end
  expect 'Ύ'.u do 'ύ'.u.upcase end
  expect 'Ὼ'.u do 'ὼ'.u.upcase end
  expect 'Ώ'.u do 'ώ'.u.upcase end
  expect 'ἈΙ'.u do 'ᾀ'.u.upcase end
  expect 'ἉΙ'.u do 'ᾁ'.u.upcase end
  expect 'ἊΙ'.u do 'ᾂ'.u.upcase end
  expect 'ἋΙ'.u do 'ᾃ'.u.upcase end
  expect 'ἌΙ'.u do 'ᾄ'.u.upcase end
  expect 'ἍΙ'.u do 'ᾅ'.u.upcase end
  expect 'ἎΙ'.u do 'ᾆ'.u.upcase end
  expect 'ἏΙ'.u do 'ᾇ'.u.upcase end
  expect 'ἈΙ'.u do 'ᾈ'.u.upcase end
  expect 'ᾀ'.u do 'ᾈ'.u.downcase end
  expect 'ἉΙ'.u do 'ᾉ'.u.upcase end
  expect 'ᾁ'.u do 'ᾉ'.u.downcase end
  expect 'ἊΙ'.u do 'ᾊ'.u.upcase end
  expect 'ᾂ'.u do 'ᾊ'.u.downcase end
  expect 'ἋΙ'.u do 'ᾋ'.u.upcase end
  expect 'ᾃ'.u do 'ᾋ'.u.downcase end
  expect 'ἌΙ'.u do 'ᾌ'.u.upcase end
  expect 'ᾄ'.u do 'ᾌ'.u.downcase end
  expect 'ἍΙ'.u do 'ᾍ'.u.upcase end
  expect 'ᾅ'.u do 'ᾍ'.u.downcase end
  expect 'ἎΙ'.u do 'ᾎ'.u.upcase end
  expect 'ᾆ'.u do 'ᾎ'.u.downcase end
  expect 'ἏΙ'.u do 'ᾏ'.u.upcase end
  expect 'ᾇ'.u do 'ᾏ'.u.downcase end
  expect 'ἨΙ'.u do 'ᾐ'.u.upcase end
  expect 'ἩΙ'.u do 'ᾑ'.u.upcase end
  expect 'ἪΙ'.u do 'ᾒ'.u.upcase end
  expect 'ἫΙ'.u do 'ᾓ'.u.upcase end
  expect 'ἬΙ'.u do 'ᾔ'.u.upcase end
  expect 'ἭΙ'.u do 'ᾕ'.u.upcase end
  expect 'ἮΙ'.u do 'ᾖ'.u.upcase end
  expect 'ἯΙ'.u do 'ᾗ'.u.upcase end
  expect 'ἨΙ'.u do 'ᾘ'.u.upcase end
  expect 'ᾐ'.u do 'ᾘ'.u.downcase end
  expect 'ἩΙ'.u do 'ᾙ'.u.upcase end
  expect 'ᾑ'.u do 'ᾙ'.u.downcase end
  expect 'ἪΙ'.u do 'ᾚ'.u.upcase end
  expect 'ᾒ'.u do 'ᾚ'.u.downcase end
  expect 'ἫΙ'.u do 'ᾛ'.u.upcase end
  expect 'ᾓ'.u do 'ᾛ'.u.downcase end
  expect 'ἬΙ'.u do 'ᾜ'.u.upcase end
  expect 'ᾔ'.u do 'ᾜ'.u.downcase end
  expect 'ἭΙ'.u do 'ᾝ'.u.upcase end
  expect 'ᾕ'.u do 'ᾝ'.u.downcase end
  expect 'ἮΙ'.u do 'ᾞ'.u.upcase end
  expect 'ᾖ'.u do 'ᾞ'.u.downcase end
  expect 'ἯΙ'.u do 'ᾟ'.u.upcase end
  expect 'ᾗ'.u do 'ᾟ'.u.downcase end
  expect 'ὨΙ'.u do 'ᾠ'.u.upcase end
  expect 'ὩΙ'.u do 'ᾡ'.u.upcase end
  expect 'ὪΙ'.u do 'ᾢ'.u.upcase end
  expect 'ὫΙ'.u do 'ᾣ'.u.upcase end
  expect 'ὬΙ'.u do 'ᾤ'.u.upcase end
  expect 'ὭΙ'.u do 'ᾥ'.u.upcase end
  expect 'ὮΙ'.u do 'ᾦ'.u.upcase end
  expect 'ὯΙ'.u do 'ᾧ'.u.upcase end
  expect 'ὨΙ'.u do 'ᾨ'.u.upcase end
  expect 'ᾠ'.u do 'ᾨ'.u.downcase end
  expect 'ὩΙ'.u do 'ᾩ'.u.upcase end
  expect 'ᾡ'.u do 'ᾩ'.u.downcase end
  expect 'ὪΙ'.u do 'ᾪ'.u.upcase end
  expect 'ᾢ'.u do 'ᾪ'.u.downcase end
  expect 'ὫΙ'.u do 'ᾫ'.u.upcase end
  expect 'ᾣ'.u do 'ᾫ'.u.downcase end
  expect 'ὬΙ'.u do 'ᾬ'.u.upcase end
  expect 'ᾤ'.u do 'ᾬ'.u.downcase end
  expect 'ὭΙ'.u do 'ᾭ'.u.upcase end
  expect 'ᾥ'.u do 'ᾭ'.u.downcase end
  expect 'ὮΙ'.u do 'ᾮ'.u.upcase end
  expect 'ᾦ'.u do 'ᾮ'.u.downcase end
  expect 'ὯΙ'.u do 'ᾯ'.u.upcase end
  expect 'ᾧ'.u do 'ᾯ'.u.downcase end
  expect 'Ᾰ'.u do 'ᾰ'.u.upcase end
  expect 'Ᾱ'.u do 'ᾱ'.u.upcase end
  expect 'ᾺΙ'.u do 'ᾲ'.u.upcase end
  expect 'ΑΙ'.u do 'ᾳ'.u.upcase end
  expect 'ΆΙ'.u do 'ᾴ'.u.upcase end
  expect 'Α͂'.u do 'ᾶ'.u.upcase end
  expect 'Α͂Ι'.u do 'ᾷ'.u.upcase end
  expect 'ᾰ'.u do 'Ᾰ'.u.downcase end
  expect 'ᾱ'.u do 'Ᾱ'.u.downcase end
  expect 'ὰ'.u do 'Ὰ'.u.downcase end
  expect 'ά'.u do 'Ά'.u.downcase end
  expect 'ΑΙ'.u do 'ᾼ'.u.upcase end
  expect 'ᾳ'.u do 'ᾼ'.u.downcase end
  expect 'Ι'.u do 'ι'.u.upcase end
  expect 'ῊΙ'.u do 'ῂ'.u.upcase end
  expect 'ΗΙ'.u do 'ῃ'.u.upcase end
  expect 'ΉΙ'.u do 'ῄ'.u.upcase end
  expect 'Η͂'.u do 'ῆ'.u.upcase end
  expect 'Η͂Ι'.u do 'ῇ'.u.upcase end
  expect 'ὲ'.u do 'Ὲ'.u.downcase end
  expect 'έ'.u do 'Έ'.u.downcase end
  expect 'ὴ'.u do 'Ὴ'.u.downcase end
  expect 'ή'.u do 'Ή'.u.downcase end
  expect 'ΗΙ'.u do 'ῌ'.u.upcase end
  expect 'ῃ'.u do 'ῌ'.u.downcase end
  expect 'Ῐ'.u do 'ῐ'.u.upcase end
  expect 'Ῑ'.u do 'ῑ'.u.upcase end
  expect 'Ϊ̀'.u do 'ῒ'.u.upcase end
  expect 'Ϊ́'.u do 'ΐ'.u.upcase end
  expect 'Ι͂'.u do 'ῖ'.u.upcase end
  expect 'Ϊ͂'.u do 'ῗ'.u.upcase end
  expect 'ῐ'.u do 'Ῐ'.u.downcase end
  expect 'ῑ'.u do 'Ῑ'.u.downcase end
  expect 'ὶ'.u do 'Ὶ'.u.downcase end
  expect 'ί'.u do 'Ί'.u.downcase end
  expect 'Ῠ'.u do 'ῠ'.u.upcase end
  expect 'Ῡ'.u do 'ῡ'.u.upcase end
  expect 'Ϋ̀'.u do 'ῢ'.u.upcase end
  expect 'Ϋ́'.u do 'ΰ'.u.upcase end
  expect 'Ρ̓'.u do 'ῤ'.u.upcase end
  expect 'Ῥ'.u do 'ῥ'.u.upcase end
  expect 'Υ͂'.u do 'ῦ'.u.upcase end
  expect 'Ϋ͂'.u do 'ῧ'.u.upcase end
  expect 'ῠ'.u do 'Ῠ'.u.downcase end
  expect 'ῡ'.u do 'Ῡ'.u.downcase end
  expect 'ὺ'.u do 'Ὺ'.u.downcase end
  expect 'ύ'.u do 'Ύ'.u.downcase end
  expect 'ῥ'.u do 'Ῥ'.u.downcase end
  expect 'ῺΙ'.u do 'ῲ'.u.upcase end
  expect 'ΩΙ'.u do 'ῳ'.u.upcase end
  expect 'ΏΙ'.u do 'ῴ'.u.upcase end
  expect 'Ω͂'.u do 'ῶ'.u.upcase end
  expect 'Ω͂Ι'.u do 'ῷ'.u.upcase end
  expect 'ὸ'.u do 'Ὸ'.u.downcase end
  expect 'ό'.u do 'Ό'.u.downcase end
  expect 'ὼ'.u do 'Ὼ'.u.downcase end
  expect 'ώ'.u do 'Ώ'.u.downcase end
  expect 'ΩΙ'.u do 'ῼ'.u.upcase end
  expect 'ῳ'.u do 'ῼ'.u.downcase end
  expect 'ω'.u do 'Ω'.u.downcase end
  expect 'k'.u do 'K'.u.downcase end
  expect 'å'.u do 'Å'.u.downcase end
  expect 'ⅎ'.u do 'Ⅎ'.u.downcase end
  expect 'Ⅎ'.u do 'ⅎ'.u.upcase end
  expect 'ↄ'.u do 'Ↄ'.u.downcase end
  expect 'Ↄ'.u do 'ↄ'.u.upcase end
  expect 'ⰰ'.u do 'Ⰰ'.u.downcase end
  expect 'ⰱ'.u do 'Ⰱ'.u.downcase end
  expect 'ⰲ'.u do 'Ⰲ'.u.downcase end
  expect 'ⰳ'.u do 'Ⰳ'.u.downcase end
  expect 'ⰴ'.u do 'Ⰴ'.u.downcase end
  expect 'ⰵ'.u do 'Ⰵ'.u.downcase end
  expect 'ⰶ'.u do 'Ⰶ'.u.downcase end
  expect 'ⰷ'.u do 'Ⰷ'.u.downcase end
  expect 'ⰸ'.u do 'Ⰸ'.u.downcase end
  expect 'ⰹ'.u do 'Ⰹ'.u.downcase end
  expect 'ⰺ'.u do 'Ⰺ'.u.downcase end
  expect 'ⰻ'.u do 'Ⰻ'.u.downcase end
  expect 'ⰼ'.u do 'Ⰼ'.u.downcase end
  expect 'ⰽ'.u do 'Ⰽ'.u.downcase end
  expect 'ⰾ'.u do 'Ⰾ'.u.downcase end
  expect 'ⰿ'.u do 'Ⰿ'.u.downcase end
  expect 'ⱀ'.u do 'Ⱀ'.u.downcase end
  expect 'ⱁ'.u do 'Ⱁ'.u.downcase end
  expect 'ⱂ'.u do 'Ⱂ'.u.downcase end
  expect 'ⱃ'.u do 'Ⱃ'.u.downcase end
  expect 'ⱄ'.u do 'Ⱄ'.u.downcase end
  expect 'ⱅ'.u do 'Ⱅ'.u.downcase end
  expect 'ⱆ'.u do 'Ⱆ'.u.downcase end
  expect 'ⱇ'.u do 'Ⱇ'.u.downcase end
  expect 'ⱈ'.u do 'Ⱈ'.u.downcase end
  expect 'ⱉ'.u do 'Ⱉ'.u.downcase end
  expect 'ⱊ'.u do 'Ⱊ'.u.downcase end
  expect 'ⱋ'.u do 'Ⱋ'.u.downcase end
  expect 'ⱌ'.u do 'Ⱌ'.u.downcase end
  expect 'ⱍ'.u do 'Ⱍ'.u.downcase end
  expect 'ⱎ'.u do 'Ⱎ'.u.downcase end
  expect 'ⱏ'.u do 'Ⱏ'.u.downcase end
  expect 'ⱐ'.u do 'Ⱐ'.u.downcase end
  expect 'ⱑ'.u do 'Ⱑ'.u.downcase end
  expect 'ⱒ'.u do 'Ⱒ'.u.downcase end
  expect 'ⱓ'.u do 'Ⱓ'.u.downcase end
  expect 'ⱔ'.u do 'Ⱔ'.u.downcase end
  expect 'ⱕ'.u do 'Ⱕ'.u.downcase end
  expect 'ⱖ'.u do 'Ⱖ'.u.downcase end
  expect 'ⱗ'.u do 'Ⱗ'.u.downcase end
  expect 'ⱘ'.u do 'Ⱘ'.u.downcase end
  expect 'ⱙ'.u do 'Ⱙ'.u.downcase end
  expect 'ⱚ'.u do 'Ⱚ'.u.downcase end
  expect 'ⱛ'.u do 'Ⱛ'.u.downcase end
  expect 'ⱜ'.u do 'Ⱜ'.u.downcase end
  expect 'ⱝ'.u do 'Ⱝ'.u.downcase end
  expect 'ⱞ'.u do 'Ⱞ'.u.downcase end
  expect 'Ⰰ'.u do 'ⰰ'.u.upcase end
  expect 'Ⰱ'.u do 'ⰱ'.u.upcase end
  expect 'Ⰲ'.u do 'ⰲ'.u.upcase end
  expect 'Ⰳ'.u do 'ⰳ'.u.upcase end
  expect 'Ⰴ'.u do 'ⰴ'.u.upcase end
  expect 'Ⰵ'.u do 'ⰵ'.u.upcase end
  expect 'Ⰶ'.u do 'ⰶ'.u.upcase end
  expect 'Ⰷ'.u do 'ⰷ'.u.upcase end
  expect 'Ⰸ'.u do 'ⰸ'.u.upcase end
  expect 'Ⰹ'.u do 'ⰹ'.u.upcase end
  expect 'Ⰺ'.u do 'ⰺ'.u.upcase end
  expect 'Ⰻ'.u do 'ⰻ'.u.upcase end
  expect 'Ⰼ'.u do 'ⰼ'.u.upcase end
  expect 'Ⰽ'.u do 'ⰽ'.u.upcase end
  expect 'Ⰾ'.u do 'ⰾ'.u.upcase end
  expect 'Ⰿ'.u do 'ⰿ'.u.upcase end
  expect 'Ⱀ'.u do 'ⱀ'.u.upcase end
  expect 'Ⱁ'.u do 'ⱁ'.u.upcase end
  expect 'Ⱂ'.u do 'ⱂ'.u.upcase end
  expect 'Ⱃ'.u do 'ⱃ'.u.upcase end
  expect 'Ⱄ'.u do 'ⱄ'.u.upcase end
  expect 'Ⱅ'.u do 'ⱅ'.u.upcase end
  expect 'Ⱆ'.u do 'ⱆ'.u.upcase end
  expect 'Ⱇ'.u do 'ⱇ'.u.upcase end
  expect 'Ⱈ'.u do 'ⱈ'.u.upcase end
  expect 'Ⱉ'.u do 'ⱉ'.u.upcase end
  expect 'Ⱊ'.u do 'ⱊ'.u.upcase end
  expect 'Ⱋ'.u do 'ⱋ'.u.upcase end
  expect 'Ⱌ'.u do 'ⱌ'.u.upcase end
  expect 'Ⱍ'.u do 'ⱍ'.u.upcase end
  expect 'Ⱎ'.u do 'ⱎ'.u.upcase end
  expect 'Ⱏ'.u do 'ⱏ'.u.upcase end
  expect 'Ⱐ'.u do 'ⱐ'.u.upcase end
  expect 'Ⱑ'.u do 'ⱑ'.u.upcase end
  expect 'Ⱒ'.u do 'ⱒ'.u.upcase end
  expect 'Ⱓ'.u do 'ⱓ'.u.upcase end
  expect 'Ⱔ'.u do 'ⱔ'.u.upcase end
  expect 'Ⱕ'.u do 'ⱕ'.u.upcase end
  expect 'Ⱖ'.u do 'ⱖ'.u.upcase end
  expect 'Ⱗ'.u do 'ⱗ'.u.upcase end
  expect 'Ⱘ'.u do 'ⱘ'.u.upcase end
  expect 'Ⱙ'.u do 'ⱙ'.u.upcase end
  expect 'Ⱚ'.u do 'ⱚ'.u.upcase end
  expect 'Ⱛ'.u do 'ⱛ'.u.upcase end
  expect 'Ⱜ'.u do 'ⱜ'.u.upcase end
  expect 'Ⱝ'.u do 'ⱝ'.u.upcase end
  expect 'Ⱞ'.u do 'ⱞ'.u.upcase end
  expect 'ⱡ'.u do 'Ⱡ'.u.downcase end
  expect 'Ⱡ'.u do 'ⱡ'.u.upcase end
  expect 'ɫ'.u do 'Ɫ'.u.downcase end
  expect 'ᵽ'.u do 'Ᵽ'.u.downcase end
  expect 'ɽ'.u do 'Ɽ'.u.downcase end
  expect 'Ⱥ'.u do 'ⱥ'.u.upcase end
  expect 'Ⱦ'.u do 'ⱦ'.u.upcase end
  expect 'ⱨ'.u do 'Ⱨ'.u.downcase end
  expect 'Ⱨ'.u do 'ⱨ'.u.upcase end
  expect 'ⱪ'.u do 'Ⱪ'.u.downcase end
  expect 'Ⱪ'.u do 'ⱪ'.u.upcase end
  expect 'ⱬ'.u do 'Ⱬ'.u.downcase end
  expect 'Ⱬ'.u do 'ⱬ'.u.upcase end
  expect 'ⱶ'.u do 'Ⱶ'.u.downcase end
  expect 'Ⱶ'.u do 'ⱶ'.u.upcase end
  expect 'ⲁ'.u do 'Ⲁ'.u.downcase end
  expect 'Ⲁ'.u do 'ⲁ'.u.upcase end
  expect 'ⲃ'.u do 'Ⲃ'.u.downcase end
  expect 'Ⲃ'.u do 'ⲃ'.u.upcase end
  expect 'ⲅ'.u do 'Ⲅ'.u.downcase end
  expect 'Ⲅ'.u do 'ⲅ'.u.upcase end
  expect 'ⲇ'.u do 'Ⲇ'.u.downcase end
  expect 'Ⲇ'.u do 'ⲇ'.u.upcase end
  expect 'ⲉ'.u do 'Ⲉ'.u.downcase end
  expect 'Ⲉ'.u do 'ⲉ'.u.upcase end
  expect 'ⲋ'.u do 'Ⲋ'.u.downcase end
  expect 'Ⲋ'.u do 'ⲋ'.u.upcase end
  expect 'ⲍ'.u do 'Ⲍ'.u.downcase end
  expect 'Ⲍ'.u do 'ⲍ'.u.upcase end
  expect 'ⲏ'.u do 'Ⲏ'.u.downcase end
  expect 'Ⲏ'.u do 'ⲏ'.u.upcase end
  expect 'ⲑ'.u do 'Ⲑ'.u.downcase end
  expect 'Ⲑ'.u do 'ⲑ'.u.upcase end
  expect 'ⲓ'.u do 'Ⲓ'.u.downcase end
  expect 'Ⲓ'.u do 'ⲓ'.u.upcase end
  expect 'ⲕ'.u do 'Ⲕ'.u.downcase end
  expect 'Ⲕ'.u do 'ⲕ'.u.upcase end
  expect 'ⲗ'.u do 'Ⲗ'.u.downcase end
  expect 'Ⲗ'.u do 'ⲗ'.u.upcase end
  expect 'ⲙ'.u do 'Ⲙ'.u.downcase end
  expect 'Ⲙ'.u do 'ⲙ'.u.upcase end
  expect 'ⲛ'.u do 'Ⲛ'.u.downcase end
  expect 'Ⲛ'.u do 'ⲛ'.u.upcase end
  expect 'ⲝ'.u do 'Ⲝ'.u.downcase end
  expect 'Ⲝ'.u do 'ⲝ'.u.upcase end
  expect 'ⲟ'.u do 'Ⲟ'.u.downcase end
  expect 'Ⲟ'.u do 'ⲟ'.u.upcase end
  expect 'ⲡ'.u do 'Ⲡ'.u.downcase end
  expect 'Ⲡ'.u do 'ⲡ'.u.upcase end
  expect 'ⲣ'.u do 'Ⲣ'.u.downcase end
  expect 'Ⲣ'.u do 'ⲣ'.u.upcase end
  expect 'ⲥ'.u do 'Ⲥ'.u.downcase end
  expect 'Ⲥ'.u do 'ⲥ'.u.upcase end
  expect 'ⲧ'.u do 'Ⲧ'.u.downcase end
  expect 'Ⲧ'.u do 'ⲧ'.u.upcase end
  expect 'ⲩ'.u do 'Ⲩ'.u.downcase end
  expect 'Ⲩ'.u do 'ⲩ'.u.upcase end
  expect 'ⲫ'.u do 'Ⲫ'.u.downcase end
  expect 'Ⲫ'.u do 'ⲫ'.u.upcase end
  expect 'ⲭ'.u do 'Ⲭ'.u.downcase end
  expect 'Ⲭ'.u do 'ⲭ'.u.upcase end
  expect 'ⲯ'.u do 'Ⲯ'.u.downcase end
  expect 'Ⲯ'.u do 'ⲯ'.u.upcase end
  expect 'ⲱ'.u do 'Ⲱ'.u.downcase end
  expect 'Ⲱ'.u do 'ⲱ'.u.upcase end
  expect 'ⲳ'.u do 'Ⲳ'.u.downcase end
  expect 'Ⲳ'.u do 'ⲳ'.u.upcase end
  expect 'ⲵ'.u do 'Ⲵ'.u.downcase end
  expect 'Ⲵ'.u do 'ⲵ'.u.upcase end
  expect 'ⲷ'.u do 'Ⲷ'.u.downcase end
  expect 'Ⲷ'.u do 'ⲷ'.u.upcase end
  expect 'ⲹ'.u do 'Ⲹ'.u.downcase end
  expect 'Ⲹ'.u do 'ⲹ'.u.upcase end
  expect 'ⲻ'.u do 'Ⲻ'.u.downcase end
  expect 'Ⲻ'.u do 'ⲻ'.u.upcase end
  expect 'ⲽ'.u do 'Ⲽ'.u.downcase end
  expect 'Ⲽ'.u do 'ⲽ'.u.upcase end
  expect 'ⲿ'.u do 'Ⲿ'.u.downcase end
  expect 'Ⲿ'.u do 'ⲿ'.u.upcase end
  expect 'ⳁ'.u do 'Ⳁ'.u.downcase end
  expect 'Ⳁ'.u do 'ⳁ'.u.upcase end
  expect 'ⳃ'.u do 'Ⳃ'.u.downcase end
  expect 'Ⳃ'.u do 'ⳃ'.u.upcase end
  expect 'ⳅ'.u do 'Ⳅ'.u.downcase end
  expect 'Ⳅ'.u do 'ⳅ'.u.upcase end
  expect 'ⳇ'.u do 'Ⳇ'.u.downcase end
  expect 'Ⳇ'.u do 'ⳇ'.u.upcase end
  expect 'ⳉ'.u do 'Ⳉ'.u.downcase end
  expect 'Ⳉ'.u do 'ⳉ'.u.upcase end
  expect 'ⳋ'.u do 'Ⳋ'.u.downcase end
  expect 'Ⳋ'.u do 'ⳋ'.u.upcase end
  expect 'ⳍ'.u do 'Ⳍ'.u.downcase end
  expect 'Ⳍ'.u do 'ⳍ'.u.upcase end
  expect 'ⳏ'.u do 'Ⳏ'.u.downcase end
  expect 'Ⳏ'.u do 'ⳏ'.u.upcase end
  expect 'ⳑ'.u do 'Ⳑ'.u.downcase end
  expect 'Ⳑ'.u do 'ⳑ'.u.upcase end
  expect 'ⳓ'.u do 'Ⳓ'.u.downcase end
  expect 'Ⳓ'.u do 'ⳓ'.u.upcase end
  expect 'ⳕ'.u do 'Ⳕ'.u.downcase end
  expect 'Ⳕ'.u do 'ⳕ'.u.upcase end
  expect 'ⳗ'.u do 'Ⳗ'.u.downcase end
  expect 'Ⳗ'.u do 'ⳗ'.u.upcase end
  expect 'ⳙ'.u do 'Ⳙ'.u.downcase end
  expect 'Ⳙ'.u do 'ⳙ'.u.upcase end
  expect 'ⳛ'.u do 'Ⳛ'.u.downcase end
  expect 'Ⳛ'.u do 'ⳛ'.u.upcase end
  expect 'ⳝ'.u do 'Ⳝ'.u.downcase end
  expect 'Ⳝ'.u do 'ⳝ'.u.upcase end
  expect 'ⳟ'.u do 'Ⳟ'.u.downcase end
  expect 'Ⳟ'.u do 'ⳟ'.u.upcase end
  expect 'ⳡ'.u do 'Ⳡ'.u.downcase end
  expect 'Ⳡ'.u do 'ⳡ'.u.upcase end
  expect 'ⳣ'.u do 'Ⳣ'.u.downcase end
  expect 'Ⳣ'.u do 'ⳣ'.u.upcase end
  expect 'Ⴀ'.u do 'ⴀ'.u.upcase end
  expect 'Ⴁ'.u do 'ⴁ'.u.upcase end
  expect 'Ⴂ'.u do 'ⴂ'.u.upcase end
  expect 'Ⴃ'.u do 'ⴃ'.u.upcase end
  expect 'Ⴄ'.u do 'ⴄ'.u.upcase end
  expect 'Ⴅ'.u do 'ⴅ'.u.upcase end
  expect 'Ⴆ'.u do 'ⴆ'.u.upcase end
  expect 'Ⴇ'.u do 'ⴇ'.u.upcase end
  expect 'Ⴈ'.u do 'ⴈ'.u.upcase end
  expect 'Ⴉ'.u do 'ⴉ'.u.upcase end
  expect 'Ⴊ'.u do 'ⴊ'.u.upcase end
  expect 'Ⴋ'.u do 'ⴋ'.u.upcase end
  expect 'Ⴌ'.u do 'ⴌ'.u.upcase end
  expect 'Ⴍ'.u do 'ⴍ'.u.upcase end
  expect 'Ⴎ'.u do 'ⴎ'.u.upcase end
  expect 'Ⴏ'.u do 'ⴏ'.u.upcase end
  expect 'Ⴐ'.u do 'ⴐ'.u.upcase end
  expect 'Ⴑ'.u do 'ⴑ'.u.upcase end
  expect 'Ⴒ'.u do 'ⴒ'.u.upcase end
  expect 'Ⴓ'.u do 'ⴓ'.u.upcase end
  expect 'Ⴔ'.u do 'ⴔ'.u.upcase end
  expect 'Ⴕ'.u do 'ⴕ'.u.upcase end
  expect 'Ⴖ'.u do 'ⴖ'.u.upcase end
  expect 'Ⴗ'.u do 'ⴗ'.u.upcase end
  expect 'Ⴘ'.u do 'ⴘ'.u.upcase end
  expect 'Ⴙ'.u do 'ⴙ'.u.upcase end
  expect 'Ⴚ'.u do 'ⴚ'.u.upcase end
  expect 'Ⴛ'.u do 'ⴛ'.u.upcase end
  expect 'Ⴜ'.u do 'ⴜ'.u.upcase end
  expect 'Ⴝ'.u do 'ⴝ'.u.upcase end
  expect 'Ⴞ'.u do 'ⴞ'.u.upcase end
  expect 'Ⴟ'.u do 'ⴟ'.u.upcase end
  expect 'Ⴠ'.u do 'ⴠ'.u.upcase end
  expect 'Ⴡ'.u do 'ⴡ'.u.upcase end
  expect 'Ⴢ'.u do 'ⴢ'.u.upcase end
  expect 'Ⴣ'.u do 'ⴣ'.u.upcase end
  expect 'Ⴤ'.u do 'ⴤ'.u.upcase end
  expect 'Ⴥ'.u do 'ⴥ'.u.upcase end
  expect 'FF'.u do 'ﬀ'.u.upcase end
  expect 'FI'.u do 'ﬁ'.u.upcase end
  expect 'FL'.u do 'ﬂ'.u.upcase end
  expect 'FFI'.u do 'ﬃ'.u.upcase end
  expect 'FFL'.u do 'ﬄ'.u.upcase end
  expect 'ST'.u do 'ﬅ'.u.upcase end
  expect 'ST'.u do 'ﬆ'.u.upcase end
  expect 'ՄՆ'.u do 'ﬓ'.u.upcase end
  expect 'ՄԵ'.u do 'ﬔ'.u.upcase end
  expect 'ՄԻ'.u do 'ﬕ'.u.upcase end
  expect 'ՎՆ'.u do 'ﬖ'.u.upcase end
  expect 'ՄԽ'.u do 'ﬗ'.u.upcase end
  expect 'ａ'.u do 'Ａ'.u.downcase end
  expect 'ｂ'.u do 'Ｂ'.u.downcase end
  expect 'ｃ'.u do 'Ｃ'.u.downcase end
  expect 'ｄ'.u do 'Ｄ'.u.downcase end
  expect 'ｅ'.u do 'Ｅ'.u.downcase end
  expect 'ｆ'.u do 'Ｆ'.u.downcase end
  expect 'ｇ'.u do 'Ｇ'.u.downcase end
  expect 'ｈ'.u do 'Ｈ'.u.downcase end
  expect 'ｉ'.u do 'Ｉ'.u.downcase end
  expect 'ｊ'.u do 'Ｊ'.u.downcase end
  expect 'ｋ'.u do 'Ｋ'.u.downcase end
  expect 'ｌ'.u do 'Ｌ'.u.downcase end
  expect 'ｍ'.u do 'Ｍ'.u.downcase end
  expect 'ｎ'.u do 'Ｎ'.u.downcase end
  expect 'ｏ'.u do 'Ｏ'.u.downcase end
  expect 'ｐ'.u do 'Ｐ'.u.downcase end
  expect 'ｑ'.u do 'Ｑ'.u.downcase end
  expect 'ｒ'.u do 'Ｒ'.u.downcase end
  expect 'ｓ'.u do 'Ｓ'.u.downcase end
  expect 'ｔ'.u do 'Ｔ'.u.downcase end
  expect 'ｕ'.u do 'Ｕ'.u.downcase end
  expect 'ｖ'.u do 'Ｖ'.u.downcase end
  expect 'ｗ'.u do 'Ｗ'.u.downcase end
  expect 'ｘ'.u do 'Ｘ'.u.downcase end
  expect 'ｙ'.u do 'Ｙ'.u.downcase end
  expect 'ｚ'.u do 'Ｚ'.u.downcase end
  expect 'Ａ'.u do 'ａ'.u.upcase end
  expect 'Ｂ'.u do 'ｂ'.u.upcase end
  expect 'Ｃ'.u do 'ｃ'.u.upcase end
  expect 'Ｄ'.u do 'ｄ'.u.upcase end
  expect 'Ｅ'.u do 'ｅ'.u.upcase end
  expect 'Ｆ'.u do 'ｆ'.u.upcase end
  expect 'Ｇ'.u do 'ｇ'.u.upcase end
  expect 'Ｈ'.u do 'ｈ'.u.upcase end
  expect 'Ｉ'.u do 'ｉ'.u.upcase end
  expect 'Ｊ'.u do 'ｊ'.u.upcase end
  expect 'Ｋ'.u do 'ｋ'.u.upcase end
  expect 'Ｌ'.u do 'ｌ'.u.upcase end
  expect 'Ｍ'.u do 'ｍ'.u.upcase end
  expect 'Ｎ'.u do 'ｎ'.u.upcase end
  expect 'Ｏ'.u do 'ｏ'.u.upcase end
  expect 'Ｐ'.u do 'ｐ'.u.upcase end
  expect 'Ｑ'.u do 'ｑ'.u.upcase end
  expect 'Ｒ'.u do 'ｒ'.u.upcase end
  expect 'Ｓ'.u do 'ｓ'.u.upcase end
  expect 'Ｔ'.u do 'ｔ'.u.upcase end
  expect 'Ｕ'.u do 'ｕ'.u.upcase end
  expect 'Ｖ'.u do 'ｖ'.u.upcase end
  expect 'Ｗ'.u do 'ｗ'.u.upcase end
  expect 'Ｘ'.u do 'ｘ'.u.upcase end
  expect 'Ｙ'.u do 'ｙ'.u.upcase end
  expect 'Ｚ'.u do 'ｚ'.u.upcase end
  expect '𐐨'.u do '𐐀'.u.downcase end
  expect '𐐩'.u do '𐐁'.u.downcase end
  expect '𐐪'.u do '𐐂'.u.downcase end
  expect '𐐫'.u do '𐐃'.u.downcase end
  expect '𐐬'.u do '𐐄'.u.downcase end
  expect '𐐭'.u do '𐐅'.u.downcase end
  expect '𐐮'.u do '𐐆'.u.downcase end
  expect '𐐯'.u do '𐐇'.u.downcase end
  expect '𐐰'.u do '𐐈'.u.downcase end
  expect '𐐱'.u do '𐐉'.u.downcase end
  expect '𐐲'.u do '𐐊'.u.downcase end
  expect '𐐳'.u do '𐐋'.u.downcase end
  expect '𐐴'.u do '𐐌'.u.downcase end
  expect '𐐵'.u do '𐐍'.u.downcase end
  expect '𐐶'.u do '𐐎'.u.downcase end
  expect '𐐷'.u do '𐐏'.u.downcase end
  expect '𐐸'.u do '𐐐'.u.downcase end
  expect '𐐹'.u do '𐐑'.u.downcase end
  expect '𐐺'.u do '𐐒'.u.downcase end
  expect '𐐻'.u do '𐐓'.u.downcase end
  expect '𐐼'.u do '𐐔'.u.downcase end
  expect '𐐽'.u do '𐐕'.u.downcase end
  expect '𐐾'.u do '𐐖'.u.downcase end
  expect '𐐿'.u do '𐐗'.u.downcase end
  expect '𐑀'.u do '𐐘'.u.downcase end
  expect '𐑁'.u do '𐐙'.u.downcase end
  expect '𐑂'.u do '𐐚'.u.downcase end
  expect '𐑃'.u do '𐐛'.u.downcase end
  expect '𐑄'.u do '𐐜'.u.downcase end
  expect '𐑅'.u do '𐐝'.u.downcase end
  expect '𐑆'.u do '𐐞'.u.downcase end
  expect '𐑇'.u do '𐐟'.u.downcase end
  expect '𐑈'.u do '𐐠'.u.downcase end
  expect '𐑉'.u do '𐐡'.u.downcase end
  expect '𐑊'.u do '𐐢'.u.downcase end
  expect '𐑋'.u do '𐐣'.u.downcase end
  expect '𐑌'.u do '𐐤'.u.downcase end
  expect '𐑍'.u do '𐐥'.u.downcase end
  expect '𐑎'.u do '𐐦'.u.downcase end
  expect '𐑏'.u do '𐐧'.u.downcase end
  expect '𐐀'.u do '𐐨'.u.upcase end
  expect '𐐁'.u do '𐐩'.u.upcase end
  expect '𐐂'.u do '𐐪'.u.upcase end
  expect '𐐃'.u do '𐐫'.u.upcase end
  expect '𐐄'.u do '𐐬'.u.upcase end
  expect '𐐅'.u do '𐐭'.u.upcase end
  expect '𐐆'.u do '𐐮'.u.upcase end
  expect '𐐇'.u do '𐐯'.u.upcase end
  expect '𐐈'.u do '𐐰'.u.upcase end
  expect '𐐉'.u do '𐐱'.u.upcase end
  expect '𐐊'.u do '𐐲'.u.upcase end
  expect '𐐋'.u do '𐐳'.u.upcase end
  expect '𐐌'.u do '𐐴'.u.upcase end
  expect '𐐍'.u do '𐐵'.u.upcase end
  expect '𐐎'.u do '𐐶'.u.upcase end
  expect '𐐏'.u do '𐐷'.u.upcase end
  expect '𐐐'.u do '𐐸'.u.upcase end
  expect '𐐑'.u do '𐐹'.u.upcase end
  expect '𐐒'.u do '𐐺'.u.upcase end
  expect '𐐓'.u do '𐐻'.u.upcase end
  expect '𐐔'.u do '𐐼'.u.upcase end
  expect '𐐕'.u do '𐐽'.u.upcase end
  expect '𐐖'.u do '𐐾'.u.upcase end
  expect '𐐗'.u do '𐐿'.u.upcase end
  expect '𐐘'.u do '𐑀'.u.upcase end
  expect '𐐙'.u do '𐑁'.u.upcase end
  expect '𐐚'.u do '𐑂'.u.upcase end
  expect '𐐛'.u do '𐑃'.u.upcase end
  expect '𐐜'.u do '𐑄'.u.upcase end
  expect '𐐝'.u do '𐑅'.u.upcase end
  expect '𐐞'.u do '𐑆'.u.upcase end
  expect '𐐟'.u do '𐑇'.u.upcase end
  expect '𐐠'.u do '𐑈'.u.upcase end
  expect '𐐡'.u do '𐑉'.u.upcase end
  expect '𐐢'.u do '𐑊'.u.upcase end
  expect '𐐣'.u do '𐑋'.u.upcase end
  expect '𐐤'.u do '𐑌'.u.upcase end
  expect '𐐥'.u do '𐑍'.u.upcase end
  expect '𐐦'.u do '𐑎'.u.upcase end
  expect '𐐧'.u do '𐑏'.u.upcase end
end
