# -*- coding: utf-8 -*-
# Automatically generated, so don’t edit!

Expectations do
  expect 'a'.u do 'A'.u.foldcase end
  expect 'b'.u do 'B'.u.foldcase end
  expect 'c'.u do 'C'.u.foldcase end
  expect 'd'.u do 'D'.u.foldcase end
  expect 'e'.u do 'E'.u.foldcase end
  expect 'f'.u do 'F'.u.foldcase end
  expect 'g'.u do 'G'.u.foldcase end
  expect 'h'.u do 'H'.u.foldcase end
  expect 'i'.u do 'I'.u.foldcase end
  expect 'j'.u do 'J'.u.foldcase end
  expect 'k'.u do 'K'.u.foldcase end
  expect 'l'.u do 'L'.u.foldcase end
  expect 'm'.u do 'M'.u.foldcase end
  expect 'n'.u do 'N'.u.foldcase end
  expect 'o'.u do 'O'.u.foldcase end
  expect 'p'.u do 'P'.u.foldcase end
  expect 'q'.u do 'Q'.u.foldcase end
  expect 'r'.u do 'R'.u.foldcase end
  expect 's'.u do 'S'.u.foldcase end
  expect 't'.u do 'T'.u.foldcase end
  expect 'u'.u do 'U'.u.foldcase end
  expect 'v'.u do 'V'.u.foldcase end
  expect 'w'.u do 'W'.u.foldcase end
  expect 'x'.u do 'X'.u.foldcase end
  expect 'y'.u do 'Y'.u.foldcase end
  expect 'z'.u do 'Z'.u.foldcase end
  expect 'μ'.u do 'µ'.u.foldcase end
  expect 'à'.u do 'À'.u.foldcase end
  expect 'á'.u do 'Á'.u.foldcase end
  expect 'â'.u do 'Â'.u.foldcase end
  expect 'ã'.u do 'Ã'.u.foldcase end
  expect 'ä'.u do 'Ä'.u.foldcase end
  expect 'å'.u do 'Å'.u.foldcase end
  expect 'æ'.u do 'Æ'.u.foldcase end
  expect 'ç'.u do 'Ç'.u.foldcase end
  expect 'è'.u do 'È'.u.foldcase end
  expect 'é'.u do 'É'.u.foldcase end
  expect 'ê'.u do 'Ê'.u.foldcase end
  expect 'ë'.u do 'Ë'.u.foldcase end
  expect 'ì'.u do 'Ì'.u.foldcase end
  expect 'í'.u do 'Í'.u.foldcase end
  expect 'î'.u do 'Î'.u.foldcase end
  expect 'ï'.u do 'Ï'.u.foldcase end
  expect 'ð'.u do 'Ð'.u.foldcase end
  expect 'ñ'.u do 'Ñ'.u.foldcase end
  expect 'ò'.u do 'Ò'.u.foldcase end
  expect 'ó'.u do 'Ó'.u.foldcase end
  expect 'ô'.u do 'Ô'.u.foldcase end
  expect 'õ'.u do 'Õ'.u.foldcase end
  expect 'ö'.u do 'Ö'.u.foldcase end
  expect 'ø'.u do 'Ø'.u.foldcase end
  expect 'ù'.u do 'Ù'.u.foldcase end
  expect 'ú'.u do 'Ú'.u.foldcase end
  expect 'û'.u do 'Û'.u.foldcase end
  expect 'ü'.u do 'Ü'.u.foldcase end
  expect 'ý'.u do 'Ý'.u.foldcase end
  expect 'þ'.u do 'Þ'.u.foldcase end
  expect 'ss'.u do 'ß'.u.foldcase end
  expect 'ā'.u do 'Ā'.u.foldcase end
  expect 'ă'.u do 'Ă'.u.foldcase end
  expect 'ą'.u do 'Ą'.u.foldcase end
  expect 'ć'.u do 'Ć'.u.foldcase end
  expect 'ĉ'.u do 'Ĉ'.u.foldcase end
  expect 'ċ'.u do 'Ċ'.u.foldcase end
  expect 'č'.u do 'Č'.u.foldcase end
  expect 'ď'.u do 'Ď'.u.foldcase end
  expect 'đ'.u do 'Đ'.u.foldcase end
  expect 'ē'.u do 'Ē'.u.foldcase end
  expect 'ĕ'.u do 'Ĕ'.u.foldcase end
  expect 'ė'.u do 'Ė'.u.foldcase end
  expect 'ę'.u do 'Ę'.u.foldcase end
  expect 'ě'.u do 'Ě'.u.foldcase end
  expect 'ĝ'.u do 'Ĝ'.u.foldcase end
  expect 'ğ'.u do 'Ğ'.u.foldcase end
  expect 'ġ'.u do 'Ġ'.u.foldcase end
  expect 'ģ'.u do 'Ģ'.u.foldcase end
  expect 'ĥ'.u do 'Ĥ'.u.foldcase end
  expect 'ħ'.u do 'Ħ'.u.foldcase end
  expect 'ĩ'.u do 'Ĩ'.u.foldcase end
  expect 'ī'.u do 'Ī'.u.foldcase end
  expect 'ĭ'.u do 'Ĭ'.u.foldcase end
  expect 'į'.u do 'Į'.u.foldcase end
  expect 'i̇'.u do 'İ'.u.foldcase end
  expect 'ĳ'.u do 'Ĳ'.u.foldcase end
  expect 'ĵ'.u do 'Ĵ'.u.foldcase end
  expect 'ķ'.u do 'Ķ'.u.foldcase end
  expect 'ĺ'.u do 'Ĺ'.u.foldcase end
  expect 'ļ'.u do 'Ļ'.u.foldcase end
  expect 'ľ'.u do 'Ľ'.u.foldcase end
  expect 'ŀ'.u do 'Ŀ'.u.foldcase end
  expect 'ł'.u do 'Ł'.u.foldcase end
  expect 'ń'.u do 'Ń'.u.foldcase end
  expect 'ņ'.u do 'Ņ'.u.foldcase end
  expect 'ň'.u do 'Ň'.u.foldcase end
  expect 'ʼn'.u do 'ŉ'.u.foldcase end
  expect 'ŋ'.u do 'Ŋ'.u.foldcase end
  expect 'ō'.u do 'Ō'.u.foldcase end
  expect 'ŏ'.u do 'Ŏ'.u.foldcase end
  expect 'ő'.u do 'Ő'.u.foldcase end
  expect 'œ'.u do 'Œ'.u.foldcase end
  expect 'ŕ'.u do 'Ŕ'.u.foldcase end
  expect 'ŗ'.u do 'Ŗ'.u.foldcase end
  expect 'ř'.u do 'Ř'.u.foldcase end
  expect 'ś'.u do 'Ś'.u.foldcase end
  expect 'ŝ'.u do 'Ŝ'.u.foldcase end
  expect 'ş'.u do 'Ş'.u.foldcase end
  expect 'š'.u do 'Š'.u.foldcase end
  expect 'ţ'.u do 'Ţ'.u.foldcase end
  expect 'ť'.u do 'Ť'.u.foldcase end
  expect 'ŧ'.u do 'Ŧ'.u.foldcase end
  expect 'ũ'.u do 'Ũ'.u.foldcase end
  expect 'ū'.u do 'Ū'.u.foldcase end
  expect 'ŭ'.u do 'Ŭ'.u.foldcase end
  expect 'ů'.u do 'Ů'.u.foldcase end
  expect 'ű'.u do 'Ű'.u.foldcase end
  expect 'ų'.u do 'Ų'.u.foldcase end
  expect 'ŵ'.u do 'Ŵ'.u.foldcase end
  expect 'ŷ'.u do 'Ŷ'.u.foldcase end
  expect 'ÿ'.u do 'Ÿ'.u.foldcase end
  expect 'ź'.u do 'Ź'.u.foldcase end
  expect 'ż'.u do 'Ż'.u.foldcase end
  expect 'ž'.u do 'Ž'.u.foldcase end
  expect 's'.u do 'ſ'.u.foldcase end
  expect 'ɓ'.u do 'Ɓ'.u.foldcase end
  expect 'ƃ'.u do 'Ƃ'.u.foldcase end
  expect 'ƅ'.u do 'Ƅ'.u.foldcase end
  expect 'ɔ'.u do 'Ɔ'.u.foldcase end
  expect 'ƈ'.u do 'Ƈ'.u.foldcase end
  expect 'ɖ'.u do 'Ɖ'.u.foldcase end
  expect 'ɗ'.u do 'Ɗ'.u.foldcase end
  expect 'ƌ'.u do 'Ƌ'.u.foldcase end
  expect 'ǝ'.u do 'Ǝ'.u.foldcase end
  expect 'ə'.u do 'Ə'.u.foldcase end
  expect 'ɛ'.u do 'Ɛ'.u.foldcase end
  expect 'ƒ'.u do 'Ƒ'.u.foldcase end
  expect 'ɠ'.u do 'Ɠ'.u.foldcase end
  expect 'ɣ'.u do 'Ɣ'.u.foldcase end
  expect 'ɩ'.u do 'Ɩ'.u.foldcase end
  expect 'ɨ'.u do 'Ɨ'.u.foldcase end
  expect 'ƙ'.u do 'Ƙ'.u.foldcase end
  expect 'ɯ'.u do 'Ɯ'.u.foldcase end
  expect 'ɲ'.u do 'Ɲ'.u.foldcase end
  expect 'ɵ'.u do 'Ɵ'.u.foldcase end
  expect 'ơ'.u do 'Ơ'.u.foldcase end
  expect 'ƣ'.u do 'Ƣ'.u.foldcase end
  expect 'ƥ'.u do 'Ƥ'.u.foldcase end
  expect 'ʀ'.u do 'Ʀ'.u.foldcase end
  expect 'ƨ'.u do 'Ƨ'.u.foldcase end
  expect 'ʃ'.u do 'Ʃ'.u.foldcase end
  expect 'ƭ'.u do 'Ƭ'.u.foldcase end
  expect 'ʈ'.u do 'Ʈ'.u.foldcase end
  expect 'ư'.u do 'Ư'.u.foldcase end
  expect 'ʊ'.u do 'Ʊ'.u.foldcase end
  expect 'ʋ'.u do 'Ʋ'.u.foldcase end
  expect 'ƴ'.u do 'Ƴ'.u.foldcase end
  expect 'ƶ'.u do 'Ƶ'.u.foldcase end
  expect 'ʒ'.u do 'Ʒ'.u.foldcase end
  expect 'ƹ'.u do 'Ƹ'.u.foldcase end
  expect 'ƽ'.u do 'Ƽ'.u.foldcase end
  expect 'ǆ'.u do 'Ǆ'.u.foldcase end
  expect 'ǆ'.u do 'ǅ'.u.foldcase end
  expect 'ǉ'.u do 'Ǉ'.u.foldcase end
  expect 'ǉ'.u do 'ǈ'.u.foldcase end
  expect 'ǌ'.u do 'Ǌ'.u.foldcase end
  expect 'ǌ'.u do 'ǋ'.u.foldcase end
  expect 'ǎ'.u do 'Ǎ'.u.foldcase end
  expect 'ǐ'.u do 'Ǐ'.u.foldcase end
  expect 'ǒ'.u do 'Ǒ'.u.foldcase end
  expect 'ǔ'.u do 'Ǔ'.u.foldcase end
  expect 'ǖ'.u do 'Ǖ'.u.foldcase end
  expect 'ǘ'.u do 'Ǘ'.u.foldcase end
  expect 'ǚ'.u do 'Ǚ'.u.foldcase end
  expect 'ǜ'.u do 'Ǜ'.u.foldcase end
  expect 'ǟ'.u do 'Ǟ'.u.foldcase end
  expect 'ǡ'.u do 'Ǡ'.u.foldcase end
  expect 'ǣ'.u do 'Ǣ'.u.foldcase end
  expect 'ǥ'.u do 'Ǥ'.u.foldcase end
  expect 'ǧ'.u do 'Ǧ'.u.foldcase end
  expect 'ǩ'.u do 'Ǩ'.u.foldcase end
  expect 'ǫ'.u do 'Ǫ'.u.foldcase end
  expect 'ǭ'.u do 'Ǭ'.u.foldcase end
  expect 'ǯ'.u do 'Ǯ'.u.foldcase end
  expect 'ǰ'.u do 'ǰ'.u.foldcase end
  expect 'ǳ'.u do 'Ǳ'.u.foldcase end
  expect 'ǳ'.u do 'ǲ'.u.foldcase end
  expect 'ǵ'.u do 'Ǵ'.u.foldcase end
  expect 'ƕ'.u do 'Ƕ'.u.foldcase end
  expect 'ƿ'.u do 'Ƿ'.u.foldcase end
  expect 'ǹ'.u do 'Ǹ'.u.foldcase end
  expect 'ǻ'.u do 'Ǻ'.u.foldcase end
  expect 'ǽ'.u do 'Ǽ'.u.foldcase end
  expect 'ǿ'.u do 'Ǿ'.u.foldcase end
  expect 'ȁ'.u do 'Ȁ'.u.foldcase end
  expect 'ȃ'.u do 'Ȃ'.u.foldcase end
  expect 'ȅ'.u do 'Ȅ'.u.foldcase end
  expect 'ȇ'.u do 'Ȇ'.u.foldcase end
  expect 'ȉ'.u do 'Ȉ'.u.foldcase end
  expect 'ȋ'.u do 'Ȋ'.u.foldcase end
  expect 'ȍ'.u do 'Ȍ'.u.foldcase end
  expect 'ȏ'.u do 'Ȏ'.u.foldcase end
  expect 'ȑ'.u do 'Ȑ'.u.foldcase end
  expect 'ȓ'.u do 'Ȓ'.u.foldcase end
  expect 'ȕ'.u do 'Ȕ'.u.foldcase end
  expect 'ȗ'.u do 'Ȗ'.u.foldcase end
  expect 'ș'.u do 'Ș'.u.foldcase end
  expect 'ț'.u do 'Ț'.u.foldcase end
  expect 'ȝ'.u do 'Ȝ'.u.foldcase end
  expect 'ȟ'.u do 'Ȟ'.u.foldcase end
  expect 'ƞ'.u do 'Ƞ'.u.foldcase end
  expect 'ȣ'.u do 'Ȣ'.u.foldcase end
  expect 'ȥ'.u do 'Ȥ'.u.foldcase end
  expect 'ȧ'.u do 'Ȧ'.u.foldcase end
  expect 'ȩ'.u do 'Ȩ'.u.foldcase end
  expect 'ȫ'.u do 'Ȫ'.u.foldcase end
  expect 'ȭ'.u do 'Ȭ'.u.foldcase end
  expect 'ȯ'.u do 'Ȯ'.u.foldcase end
  expect 'ȱ'.u do 'Ȱ'.u.foldcase end
  expect 'ȳ'.u do 'Ȳ'.u.foldcase end
  expect 'ⱥ'.u do 'Ⱥ'.u.foldcase end
  expect 'ȼ'.u do 'Ȼ'.u.foldcase end
  expect 'ƚ'.u do 'Ƚ'.u.foldcase end
  expect 'ⱦ'.u do 'Ⱦ'.u.foldcase end
  expect 'ɂ'.u do 'Ɂ'.u.foldcase end
  expect 'ƀ'.u do 'Ƀ'.u.foldcase end
  expect 'ʉ'.u do 'Ʉ'.u.foldcase end
  expect 'ʌ'.u do 'Ʌ'.u.foldcase end
  expect 'ɇ'.u do 'Ɇ'.u.foldcase end
  expect 'ɉ'.u do 'Ɉ'.u.foldcase end
  expect 'ɋ'.u do 'Ɋ'.u.foldcase end
  expect 'ɍ'.u do 'Ɍ'.u.foldcase end
  expect 'ɏ'.u do 'Ɏ'.u.foldcase end
  expect 'ι'.u do 'ͅ'.u.foldcase end
  expect 'ά'.u do 'Ά'.u.foldcase end
  expect 'έ'.u do 'Έ'.u.foldcase end
  expect 'ή'.u do 'Ή'.u.foldcase end
  expect 'ί'.u do 'Ί'.u.foldcase end
  expect 'ό'.u do 'Ό'.u.foldcase end
  expect 'ύ'.u do 'Ύ'.u.foldcase end
  expect 'ώ'.u do 'Ώ'.u.foldcase end
  expect 'ΐ'.u do 'ΐ'.u.foldcase end
  expect 'α'.u do 'Α'.u.foldcase end
  expect 'β'.u do 'Β'.u.foldcase end
  expect 'γ'.u do 'Γ'.u.foldcase end
  expect 'δ'.u do 'Δ'.u.foldcase end
  expect 'ε'.u do 'Ε'.u.foldcase end
  expect 'ζ'.u do 'Ζ'.u.foldcase end
  expect 'η'.u do 'Η'.u.foldcase end
  expect 'θ'.u do 'Θ'.u.foldcase end
  expect 'ι'.u do 'Ι'.u.foldcase end
  expect 'κ'.u do 'Κ'.u.foldcase end
  expect 'λ'.u do 'Λ'.u.foldcase end
  expect 'μ'.u do 'Μ'.u.foldcase end
  expect 'ν'.u do 'Ν'.u.foldcase end
  expect 'ξ'.u do 'Ξ'.u.foldcase end
  expect 'ο'.u do 'Ο'.u.foldcase end
  expect 'π'.u do 'Π'.u.foldcase end
  expect 'ρ'.u do 'Ρ'.u.foldcase end
  expect 'σ'.u do 'Σ'.u.foldcase end
  expect 'τ'.u do 'Τ'.u.foldcase end
  expect 'υ'.u do 'Υ'.u.foldcase end
  expect 'φ'.u do 'Φ'.u.foldcase end
  expect 'χ'.u do 'Χ'.u.foldcase end
  expect 'ψ'.u do 'Ψ'.u.foldcase end
  expect 'ω'.u do 'Ω'.u.foldcase end
  expect 'ϊ'.u do 'Ϊ'.u.foldcase end
  expect 'ϋ'.u do 'Ϋ'.u.foldcase end
  expect 'ΰ'.u do 'ΰ'.u.foldcase end
  expect 'σ'.u do 'ς'.u.foldcase end
  expect 'β'.u do 'ϐ'.u.foldcase end
  expect 'θ'.u do 'ϑ'.u.foldcase end
  expect 'φ'.u do 'ϕ'.u.foldcase end
  expect 'π'.u do 'ϖ'.u.foldcase end
  expect 'ϙ'.u do 'Ϙ'.u.foldcase end
  expect 'ϛ'.u do 'Ϛ'.u.foldcase end
  expect 'ϝ'.u do 'Ϝ'.u.foldcase end
  expect 'ϟ'.u do 'Ϟ'.u.foldcase end
  expect 'ϡ'.u do 'Ϡ'.u.foldcase end
  expect 'ϣ'.u do 'Ϣ'.u.foldcase end
  expect 'ϥ'.u do 'Ϥ'.u.foldcase end
  expect 'ϧ'.u do 'Ϧ'.u.foldcase end
  expect 'ϩ'.u do 'Ϩ'.u.foldcase end
  expect 'ϫ'.u do 'Ϫ'.u.foldcase end
  expect 'ϭ'.u do 'Ϭ'.u.foldcase end
  expect 'ϯ'.u do 'Ϯ'.u.foldcase end
  expect 'κ'.u do 'ϰ'.u.foldcase end
  expect 'ρ'.u do 'ϱ'.u.foldcase end
  expect 'θ'.u do 'ϴ'.u.foldcase end
  expect 'ε'.u do 'ϵ'.u.foldcase end
  expect 'ϸ'.u do 'Ϸ'.u.foldcase end
  expect 'ϲ'.u do 'Ϲ'.u.foldcase end
  expect 'ϻ'.u do 'Ϻ'.u.foldcase end
  expect 'ͻ'.u do 'Ͻ'.u.foldcase end
  expect 'ͼ'.u do 'Ͼ'.u.foldcase end
  expect 'ͽ'.u do 'Ͽ'.u.foldcase end
  expect 'ѐ'.u do 'Ѐ'.u.foldcase end
  expect 'ё'.u do 'Ё'.u.foldcase end
  expect 'ђ'.u do 'Ђ'.u.foldcase end
  expect 'ѓ'.u do 'Ѓ'.u.foldcase end
  expect 'є'.u do 'Є'.u.foldcase end
  expect 'ѕ'.u do 'Ѕ'.u.foldcase end
  expect 'і'.u do 'І'.u.foldcase end
  expect 'ї'.u do 'Ї'.u.foldcase end
  expect 'ј'.u do 'Ј'.u.foldcase end
  expect 'љ'.u do 'Љ'.u.foldcase end
  expect 'њ'.u do 'Њ'.u.foldcase end
  expect 'ћ'.u do 'Ћ'.u.foldcase end
  expect 'ќ'.u do 'Ќ'.u.foldcase end
  expect 'ѝ'.u do 'Ѝ'.u.foldcase end
  expect 'ў'.u do 'Ў'.u.foldcase end
  expect 'џ'.u do 'Џ'.u.foldcase end
  expect 'а'.u do 'А'.u.foldcase end
  expect 'б'.u do 'Б'.u.foldcase end
  expect 'в'.u do 'В'.u.foldcase end
  expect 'г'.u do 'Г'.u.foldcase end
  expect 'д'.u do 'Д'.u.foldcase end
  expect 'е'.u do 'Е'.u.foldcase end
  expect 'ж'.u do 'Ж'.u.foldcase end
  expect 'з'.u do 'З'.u.foldcase end
  expect 'и'.u do 'И'.u.foldcase end
  expect 'й'.u do 'Й'.u.foldcase end
  expect 'к'.u do 'К'.u.foldcase end
  expect 'л'.u do 'Л'.u.foldcase end
  expect 'м'.u do 'М'.u.foldcase end
  expect 'н'.u do 'Н'.u.foldcase end
  expect 'о'.u do 'О'.u.foldcase end
  expect 'п'.u do 'П'.u.foldcase end
  expect 'р'.u do 'Р'.u.foldcase end
  expect 'с'.u do 'С'.u.foldcase end
  expect 'т'.u do 'Т'.u.foldcase end
  expect 'у'.u do 'У'.u.foldcase end
  expect 'ф'.u do 'Ф'.u.foldcase end
  expect 'х'.u do 'Х'.u.foldcase end
  expect 'ц'.u do 'Ц'.u.foldcase end
  expect 'ч'.u do 'Ч'.u.foldcase end
  expect 'ш'.u do 'Ш'.u.foldcase end
  expect 'щ'.u do 'Щ'.u.foldcase end
  expect 'ъ'.u do 'Ъ'.u.foldcase end
  expect 'ы'.u do 'Ы'.u.foldcase end
  expect 'ь'.u do 'Ь'.u.foldcase end
  expect 'э'.u do 'Э'.u.foldcase end
  expect 'ю'.u do 'Ю'.u.foldcase end
  expect 'я'.u do 'Я'.u.foldcase end
  expect 'ѡ'.u do 'Ѡ'.u.foldcase end
  expect 'ѣ'.u do 'Ѣ'.u.foldcase end
  expect 'ѥ'.u do 'Ѥ'.u.foldcase end
  expect 'ѧ'.u do 'Ѧ'.u.foldcase end
  expect 'ѩ'.u do 'Ѩ'.u.foldcase end
  expect 'ѫ'.u do 'Ѫ'.u.foldcase end
  expect 'ѭ'.u do 'Ѭ'.u.foldcase end
  expect 'ѯ'.u do 'Ѯ'.u.foldcase end
  expect 'ѱ'.u do 'Ѱ'.u.foldcase end
  expect 'ѳ'.u do 'Ѳ'.u.foldcase end
  expect 'ѵ'.u do 'Ѵ'.u.foldcase end
  expect 'ѷ'.u do 'Ѷ'.u.foldcase end
  expect 'ѹ'.u do 'Ѹ'.u.foldcase end
  expect 'ѻ'.u do 'Ѻ'.u.foldcase end
  expect 'ѽ'.u do 'Ѽ'.u.foldcase end
  expect 'ѿ'.u do 'Ѿ'.u.foldcase end
  expect 'ҁ'.u do 'Ҁ'.u.foldcase end
  expect 'ҋ'.u do 'Ҋ'.u.foldcase end
  expect 'ҍ'.u do 'Ҍ'.u.foldcase end
  expect 'ҏ'.u do 'Ҏ'.u.foldcase end
  expect 'ґ'.u do 'Ґ'.u.foldcase end
  expect 'ғ'.u do 'Ғ'.u.foldcase end
  expect 'ҕ'.u do 'Ҕ'.u.foldcase end
  expect 'җ'.u do 'Җ'.u.foldcase end
  expect 'ҙ'.u do 'Ҙ'.u.foldcase end
  expect 'қ'.u do 'Қ'.u.foldcase end
  expect 'ҝ'.u do 'Ҝ'.u.foldcase end
  expect 'ҟ'.u do 'Ҟ'.u.foldcase end
  expect 'ҡ'.u do 'Ҡ'.u.foldcase end
  expect 'ң'.u do 'Ң'.u.foldcase end
  expect 'ҥ'.u do 'Ҥ'.u.foldcase end
  expect 'ҧ'.u do 'Ҧ'.u.foldcase end
  expect 'ҩ'.u do 'Ҩ'.u.foldcase end
  expect 'ҫ'.u do 'Ҫ'.u.foldcase end
  expect 'ҭ'.u do 'Ҭ'.u.foldcase end
  expect 'ү'.u do 'Ү'.u.foldcase end
  expect 'ұ'.u do 'Ұ'.u.foldcase end
  expect 'ҳ'.u do 'Ҳ'.u.foldcase end
  expect 'ҵ'.u do 'Ҵ'.u.foldcase end
  expect 'ҷ'.u do 'Ҷ'.u.foldcase end
  expect 'ҹ'.u do 'Ҹ'.u.foldcase end
  expect 'һ'.u do 'Һ'.u.foldcase end
  expect 'ҽ'.u do 'Ҽ'.u.foldcase end
  expect 'ҿ'.u do 'Ҿ'.u.foldcase end
  expect 'ӏ'.u do 'Ӏ'.u.foldcase end
  expect 'ӂ'.u do 'Ӂ'.u.foldcase end
  expect 'ӄ'.u do 'Ӄ'.u.foldcase end
  expect 'ӆ'.u do 'Ӆ'.u.foldcase end
  expect 'ӈ'.u do 'Ӈ'.u.foldcase end
  expect 'ӊ'.u do 'Ӊ'.u.foldcase end
  expect 'ӌ'.u do 'Ӌ'.u.foldcase end
  expect 'ӎ'.u do 'Ӎ'.u.foldcase end
  expect 'ӑ'.u do 'Ӑ'.u.foldcase end
  expect 'ӓ'.u do 'Ӓ'.u.foldcase end
  expect 'ӕ'.u do 'Ӕ'.u.foldcase end
  expect 'ӗ'.u do 'Ӗ'.u.foldcase end
  expect 'ә'.u do 'Ә'.u.foldcase end
  expect 'ӛ'.u do 'Ӛ'.u.foldcase end
  expect 'ӝ'.u do 'Ӝ'.u.foldcase end
  expect 'ӟ'.u do 'Ӟ'.u.foldcase end
  expect 'ӡ'.u do 'Ӡ'.u.foldcase end
  expect 'ӣ'.u do 'Ӣ'.u.foldcase end
  expect 'ӥ'.u do 'Ӥ'.u.foldcase end
  expect 'ӧ'.u do 'Ӧ'.u.foldcase end
  expect 'ө'.u do 'Ө'.u.foldcase end
  expect 'ӫ'.u do 'Ӫ'.u.foldcase end
  expect 'ӭ'.u do 'Ӭ'.u.foldcase end
  expect 'ӯ'.u do 'Ӯ'.u.foldcase end
  expect 'ӱ'.u do 'Ӱ'.u.foldcase end
  expect 'ӳ'.u do 'Ӳ'.u.foldcase end
  expect 'ӵ'.u do 'Ӵ'.u.foldcase end
  expect 'ӷ'.u do 'Ӷ'.u.foldcase end
  expect 'ӹ'.u do 'Ӹ'.u.foldcase end
  expect 'ӻ'.u do 'Ӻ'.u.foldcase end
  expect 'ӽ'.u do 'Ӽ'.u.foldcase end
  expect 'ӿ'.u do 'Ӿ'.u.foldcase end
  expect 'ԁ'.u do 'Ԁ'.u.foldcase end
  expect 'ԃ'.u do 'Ԃ'.u.foldcase end
  expect 'ԅ'.u do 'Ԅ'.u.foldcase end
  expect 'ԇ'.u do 'Ԇ'.u.foldcase end
  expect 'ԉ'.u do 'Ԉ'.u.foldcase end
  expect 'ԋ'.u do 'Ԋ'.u.foldcase end
  expect 'ԍ'.u do 'Ԍ'.u.foldcase end
  expect 'ԏ'.u do 'Ԏ'.u.foldcase end
  expect 'ԑ'.u do 'Ԑ'.u.foldcase end
  expect 'ԓ'.u do 'Ԓ'.u.foldcase end
  expect 'ա'.u do 'Ա'.u.foldcase end
  expect 'բ'.u do 'Բ'.u.foldcase end
  expect 'գ'.u do 'Գ'.u.foldcase end
  expect 'դ'.u do 'Դ'.u.foldcase end
  expect 'ե'.u do 'Ե'.u.foldcase end
  expect 'զ'.u do 'Զ'.u.foldcase end
  expect 'է'.u do 'Է'.u.foldcase end
  expect 'ը'.u do 'Ը'.u.foldcase end
  expect 'թ'.u do 'Թ'.u.foldcase end
  expect 'ժ'.u do 'Ժ'.u.foldcase end
  expect 'ի'.u do 'Ի'.u.foldcase end
  expect 'լ'.u do 'Լ'.u.foldcase end
  expect 'խ'.u do 'Խ'.u.foldcase end
  expect 'ծ'.u do 'Ծ'.u.foldcase end
  expect 'կ'.u do 'Կ'.u.foldcase end
  expect 'հ'.u do 'Հ'.u.foldcase end
  expect 'ձ'.u do 'Ձ'.u.foldcase end
  expect 'ղ'.u do 'Ղ'.u.foldcase end
  expect 'ճ'.u do 'Ճ'.u.foldcase end
  expect 'մ'.u do 'Մ'.u.foldcase end
  expect 'յ'.u do 'Յ'.u.foldcase end
  expect 'ն'.u do 'Ն'.u.foldcase end
  expect 'շ'.u do 'Շ'.u.foldcase end
  expect 'ո'.u do 'Ո'.u.foldcase end
  expect 'չ'.u do 'Չ'.u.foldcase end
  expect 'պ'.u do 'Պ'.u.foldcase end
  expect 'ջ'.u do 'Ջ'.u.foldcase end
  expect 'ռ'.u do 'Ռ'.u.foldcase end
  expect 'ս'.u do 'Ս'.u.foldcase end
  expect 'վ'.u do 'Վ'.u.foldcase end
  expect 'տ'.u do 'Տ'.u.foldcase end
  expect 'ր'.u do 'Ր'.u.foldcase end
  expect 'ց'.u do 'Ց'.u.foldcase end
  expect 'ւ'.u do 'Ւ'.u.foldcase end
  expect 'փ'.u do 'Փ'.u.foldcase end
  expect 'ք'.u do 'Ք'.u.foldcase end
  expect 'օ'.u do 'Օ'.u.foldcase end
  expect 'ֆ'.u do 'Ֆ'.u.foldcase end
  expect 'եւ'.u do 'և'.u.foldcase end
  expect 'ⴀ'.u do 'Ⴀ'.u.foldcase end
  expect 'ⴁ'.u do 'Ⴁ'.u.foldcase end
  expect 'ⴂ'.u do 'Ⴂ'.u.foldcase end
  expect 'ⴃ'.u do 'Ⴃ'.u.foldcase end
  expect 'ⴄ'.u do 'Ⴄ'.u.foldcase end
  expect 'ⴅ'.u do 'Ⴅ'.u.foldcase end
  expect 'ⴆ'.u do 'Ⴆ'.u.foldcase end
  expect 'ⴇ'.u do 'Ⴇ'.u.foldcase end
  expect 'ⴈ'.u do 'Ⴈ'.u.foldcase end
  expect 'ⴉ'.u do 'Ⴉ'.u.foldcase end
  expect 'ⴊ'.u do 'Ⴊ'.u.foldcase end
  expect 'ⴋ'.u do 'Ⴋ'.u.foldcase end
  expect 'ⴌ'.u do 'Ⴌ'.u.foldcase end
  expect 'ⴍ'.u do 'Ⴍ'.u.foldcase end
  expect 'ⴎ'.u do 'Ⴎ'.u.foldcase end
  expect 'ⴏ'.u do 'Ⴏ'.u.foldcase end
  expect 'ⴐ'.u do 'Ⴐ'.u.foldcase end
  expect 'ⴑ'.u do 'Ⴑ'.u.foldcase end
  expect 'ⴒ'.u do 'Ⴒ'.u.foldcase end
  expect 'ⴓ'.u do 'Ⴓ'.u.foldcase end
  expect 'ⴔ'.u do 'Ⴔ'.u.foldcase end
  expect 'ⴕ'.u do 'Ⴕ'.u.foldcase end
  expect 'ⴖ'.u do 'Ⴖ'.u.foldcase end
  expect 'ⴗ'.u do 'Ⴗ'.u.foldcase end
  expect 'ⴘ'.u do 'Ⴘ'.u.foldcase end
  expect 'ⴙ'.u do 'Ⴙ'.u.foldcase end
  expect 'ⴚ'.u do 'Ⴚ'.u.foldcase end
  expect 'ⴛ'.u do 'Ⴛ'.u.foldcase end
  expect 'ⴜ'.u do 'Ⴜ'.u.foldcase end
  expect 'ⴝ'.u do 'Ⴝ'.u.foldcase end
  expect 'ⴞ'.u do 'Ⴞ'.u.foldcase end
  expect 'ⴟ'.u do 'Ⴟ'.u.foldcase end
  expect 'ⴠ'.u do 'Ⴠ'.u.foldcase end
  expect 'ⴡ'.u do 'Ⴡ'.u.foldcase end
  expect 'ⴢ'.u do 'Ⴢ'.u.foldcase end
  expect 'ⴣ'.u do 'Ⴣ'.u.foldcase end
  expect 'ⴤ'.u do 'Ⴤ'.u.foldcase end
  expect 'ⴥ'.u do 'Ⴥ'.u.foldcase end
  expect 'ḁ'.u do 'Ḁ'.u.foldcase end
  expect 'ḃ'.u do 'Ḃ'.u.foldcase end
  expect 'ḅ'.u do 'Ḅ'.u.foldcase end
  expect 'ḇ'.u do 'Ḇ'.u.foldcase end
  expect 'ḉ'.u do 'Ḉ'.u.foldcase end
  expect 'ḋ'.u do 'Ḋ'.u.foldcase end
  expect 'ḍ'.u do 'Ḍ'.u.foldcase end
  expect 'ḏ'.u do 'Ḏ'.u.foldcase end
  expect 'ḑ'.u do 'Ḑ'.u.foldcase end
  expect 'ḓ'.u do 'Ḓ'.u.foldcase end
  expect 'ḕ'.u do 'Ḕ'.u.foldcase end
  expect 'ḗ'.u do 'Ḗ'.u.foldcase end
  expect 'ḙ'.u do 'Ḙ'.u.foldcase end
  expect 'ḛ'.u do 'Ḛ'.u.foldcase end
  expect 'ḝ'.u do 'Ḝ'.u.foldcase end
  expect 'ḟ'.u do 'Ḟ'.u.foldcase end
  expect 'ḡ'.u do 'Ḡ'.u.foldcase end
  expect 'ḣ'.u do 'Ḣ'.u.foldcase end
  expect 'ḥ'.u do 'Ḥ'.u.foldcase end
  expect 'ḧ'.u do 'Ḧ'.u.foldcase end
  expect 'ḩ'.u do 'Ḩ'.u.foldcase end
  expect 'ḫ'.u do 'Ḫ'.u.foldcase end
  expect 'ḭ'.u do 'Ḭ'.u.foldcase end
  expect 'ḯ'.u do 'Ḯ'.u.foldcase end
  expect 'ḱ'.u do 'Ḱ'.u.foldcase end
  expect 'ḳ'.u do 'Ḳ'.u.foldcase end
  expect 'ḵ'.u do 'Ḵ'.u.foldcase end
  expect 'ḷ'.u do 'Ḷ'.u.foldcase end
  expect 'ḹ'.u do 'Ḹ'.u.foldcase end
  expect 'ḻ'.u do 'Ḻ'.u.foldcase end
  expect 'ḽ'.u do 'Ḽ'.u.foldcase end
  expect 'ḿ'.u do 'Ḿ'.u.foldcase end
  expect 'ṁ'.u do 'Ṁ'.u.foldcase end
  expect 'ṃ'.u do 'Ṃ'.u.foldcase end
  expect 'ṅ'.u do 'Ṅ'.u.foldcase end
  expect 'ṇ'.u do 'Ṇ'.u.foldcase end
  expect 'ṉ'.u do 'Ṉ'.u.foldcase end
  expect 'ṋ'.u do 'Ṋ'.u.foldcase end
  expect 'ṍ'.u do 'Ṍ'.u.foldcase end
  expect 'ṏ'.u do 'Ṏ'.u.foldcase end
  expect 'ṑ'.u do 'Ṑ'.u.foldcase end
  expect 'ṓ'.u do 'Ṓ'.u.foldcase end
  expect 'ṕ'.u do 'Ṕ'.u.foldcase end
  expect 'ṗ'.u do 'Ṗ'.u.foldcase end
  expect 'ṙ'.u do 'Ṙ'.u.foldcase end
  expect 'ṛ'.u do 'Ṛ'.u.foldcase end
  expect 'ṝ'.u do 'Ṝ'.u.foldcase end
  expect 'ṟ'.u do 'Ṟ'.u.foldcase end
  expect 'ṡ'.u do 'Ṡ'.u.foldcase end
  expect 'ṣ'.u do 'Ṣ'.u.foldcase end
  expect 'ṥ'.u do 'Ṥ'.u.foldcase end
  expect 'ṧ'.u do 'Ṧ'.u.foldcase end
  expect 'ṩ'.u do 'Ṩ'.u.foldcase end
  expect 'ṫ'.u do 'Ṫ'.u.foldcase end
  expect 'ṭ'.u do 'Ṭ'.u.foldcase end
  expect 'ṯ'.u do 'Ṯ'.u.foldcase end
  expect 'ṱ'.u do 'Ṱ'.u.foldcase end
  expect 'ṳ'.u do 'Ṳ'.u.foldcase end
  expect 'ṵ'.u do 'Ṵ'.u.foldcase end
  expect 'ṷ'.u do 'Ṷ'.u.foldcase end
  expect 'ṹ'.u do 'Ṹ'.u.foldcase end
  expect 'ṻ'.u do 'Ṻ'.u.foldcase end
  expect 'ṽ'.u do 'Ṽ'.u.foldcase end
  expect 'ṿ'.u do 'Ṿ'.u.foldcase end
  expect 'ẁ'.u do 'Ẁ'.u.foldcase end
  expect 'ẃ'.u do 'Ẃ'.u.foldcase end
  expect 'ẅ'.u do 'Ẅ'.u.foldcase end
  expect 'ẇ'.u do 'Ẇ'.u.foldcase end
  expect 'ẉ'.u do 'Ẉ'.u.foldcase end
  expect 'ẋ'.u do 'Ẋ'.u.foldcase end
  expect 'ẍ'.u do 'Ẍ'.u.foldcase end
  expect 'ẏ'.u do 'Ẏ'.u.foldcase end
  expect 'ẑ'.u do 'Ẑ'.u.foldcase end
  expect 'ẓ'.u do 'Ẓ'.u.foldcase end
  expect 'ẕ'.u do 'Ẕ'.u.foldcase end
  expect 'ẖ'.u do 'ẖ'.u.foldcase end
  expect 'ẗ'.u do 'ẗ'.u.foldcase end
  expect 'ẘ'.u do 'ẘ'.u.foldcase end
  expect 'ẙ'.u do 'ẙ'.u.foldcase end
  expect 'aʾ'.u do 'ẚ'.u.foldcase end
  expect 'ṡ'.u do 'ẛ'.u.foldcase end
  expect 'ạ'.u do 'Ạ'.u.foldcase end
  expect 'ả'.u do 'Ả'.u.foldcase end
  expect 'ấ'.u do 'Ấ'.u.foldcase end
  expect 'ầ'.u do 'Ầ'.u.foldcase end
  expect 'ẩ'.u do 'Ẩ'.u.foldcase end
  expect 'ẫ'.u do 'Ẫ'.u.foldcase end
  expect 'ậ'.u do 'Ậ'.u.foldcase end
  expect 'ắ'.u do 'Ắ'.u.foldcase end
  expect 'ằ'.u do 'Ằ'.u.foldcase end
  expect 'ẳ'.u do 'Ẳ'.u.foldcase end
  expect 'ẵ'.u do 'Ẵ'.u.foldcase end
  expect 'ặ'.u do 'Ặ'.u.foldcase end
  expect 'ẹ'.u do 'Ẹ'.u.foldcase end
  expect 'ẻ'.u do 'Ẻ'.u.foldcase end
  expect 'ẽ'.u do 'Ẽ'.u.foldcase end
  expect 'ế'.u do 'Ế'.u.foldcase end
  expect 'ề'.u do 'Ề'.u.foldcase end
  expect 'ể'.u do 'Ể'.u.foldcase end
  expect 'ễ'.u do 'Ễ'.u.foldcase end
  expect 'ệ'.u do 'Ệ'.u.foldcase end
  expect 'ỉ'.u do 'Ỉ'.u.foldcase end
  expect 'ị'.u do 'Ị'.u.foldcase end
  expect 'ọ'.u do 'Ọ'.u.foldcase end
  expect 'ỏ'.u do 'Ỏ'.u.foldcase end
  expect 'ố'.u do 'Ố'.u.foldcase end
  expect 'ồ'.u do 'Ồ'.u.foldcase end
  expect 'ổ'.u do 'Ổ'.u.foldcase end
  expect 'ỗ'.u do 'Ỗ'.u.foldcase end
  expect 'ộ'.u do 'Ộ'.u.foldcase end
  expect 'ớ'.u do 'Ớ'.u.foldcase end
  expect 'ờ'.u do 'Ờ'.u.foldcase end
  expect 'ở'.u do 'Ở'.u.foldcase end
  expect 'ỡ'.u do 'Ỡ'.u.foldcase end
  expect 'ợ'.u do 'Ợ'.u.foldcase end
  expect 'ụ'.u do 'Ụ'.u.foldcase end
  expect 'ủ'.u do 'Ủ'.u.foldcase end
  expect 'ứ'.u do 'Ứ'.u.foldcase end
  expect 'ừ'.u do 'Ừ'.u.foldcase end
  expect 'ử'.u do 'Ử'.u.foldcase end
  expect 'ữ'.u do 'Ữ'.u.foldcase end
  expect 'ự'.u do 'Ự'.u.foldcase end
  expect 'ỳ'.u do 'Ỳ'.u.foldcase end
  expect 'ỵ'.u do 'Ỵ'.u.foldcase end
  expect 'ỷ'.u do 'Ỷ'.u.foldcase end
  expect 'ỹ'.u do 'Ỹ'.u.foldcase end
  expect 'ἀ'.u do 'Ἀ'.u.foldcase end
  expect 'ἁ'.u do 'Ἁ'.u.foldcase end
  expect 'ἂ'.u do 'Ἂ'.u.foldcase end
  expect 'ἃ'.u do 'Ἃ'.u.foldcase end
  expect 'ἄ'.u do 'Ἄ'.u.foldcase end
  expect 'ἅ'.u do 'Ἅ'.u.foldcase end
  expect 'ἆ'.u do 'Ἆ'.u.foldcase end
  expect 'ἇ'.u do 'Ἇ'.u.foldcase end
  expect 'ἐ'.u do 'Ἐ'.u.foldcase end
  expect 'ἑ'.u do 'Ἑ'.u.foldcase end
  expect 'ἒ'.u do 'Ἒ'.u.foldcase end
  expect 'ἓ'.u do 'Ἓ'.u.foldcase end
  expect 'ἔ'.u do 'Ἔ'.u.foldcase end
  expect 'ἕ'.u do 'Ἕ'.u.foldcase end
  expect 'ἠ'.u do 'Ἠ'.u.foldcase end
  expect 'ἡ'.u do 'Ἡ'.u.foldcase end
  expect 'ἢ'.u do 'Ἢ'.u.foldcase end
  expect 'ἣ'.u do 'Ἣ'.u.foldcase end
  expect 'ἤ'.u do 'Ἤ'.u.foldcase end
  expect 'ἥ'.u do 'Ἥ'.u.foldcase end
  expect 'ἦ'.u do 'Ἦ'.u.foldcase end
  expect 'ἧ'.u do 'Ἧ'.u.foldcase end
  expect 'ἰ'.u do 'Ἰ'.u.foldcase end
  expect 'ἱ'.u do 'Ἱ'.u.foldcase end
  expect 'ἲ'.u do 'Ἲ'.u.foldcase end
  expect 'ἳ'.u do 'Ἳ'.u.foldcase end
  expect 'ἴ'.u do 'Ἴ'.u.foldcase end
  expect 'ἵ'.u do 'Ἵ'.u.foldcase end
  expect 'ἶ'.u do 'Ἶ'.u.foldcase end
  expect 'ἷ'.u do 'Ἷ'.u.foldcase end
  expect 'ὀ'.u do 'Ὀ'.u.foldcase end
  expect 'ὁ'.u do 'Ὁ'.u.foldcase end
  expect 'ὂ'.u do 'Ὂ'.u.foldcase end
  expect 'ὃ'.u do 'Ὃ'.u.foldcase end
  expect 'ὄ'.u do 'Ὄ'.u.foldcase end
  expect 'ὅ'.u do 'Ὅ'.u.foldcase end
  expect 'ὐ'.u do 'ὐ'.u.foldcase end
  expect 'ὒ'.u do 'ὒ'.u.foldcase end
  expect 'ὔ'.u do 'ὔ'.u.foldcase end
  expect 'ὖ'.u do 'ὖ'.u.foldcase end
  expect 'ὑ'.u do 'Ὑ'.u.foldcase end
  expect 'ὓ'.u do 'Ὓ'.u.foldcase end
  expect 'ὕ'.u do 'Ὕ'.u.foldcase end
  expect 'ὗ'.u do 'Ὗ'.u.foldcase end
  expect 'ὠ'.u do 'Ὠ'.u.foldcase end
  expect 'ὡ'.u do 'Ὡ'.u.foldcase end
  expect 'ὢ'.u do 'Ὢ'.u.foldcase end
  expect 'ὣ'.u do 'Ὣ'.u.foldcase end
  expect 'ὤ'.u do 'Ὤ'.u.foldcase end
  expect 'ὥ'.u do 'Ὥ'.u.foldcase end
  expect 'ὦ'.u do 'Ὦ'.u.foldcase end
  expect 'ὧ'.u do 'Ὧ'.u.foldcase end
  expect 'ἀι'.u do 'ᾀ'.u.foldcase end
  expect 'ἁι'.u do 'ᾁ'.u.foldcase end
  expect 'ἂι'.u do 'ᾂ'.u.foldcase end
  expect 'ἃι'.u do 'ᾃ'.u.foldcase end
  expect 'ἄι'.u do 'ᾄ'.u.foldcase end
  expect 'ἅι'.u do 'ᾅ'.u.foldcase end
  expect 'ἆι'.u do 'ᾆ'.u.foldcase end
  expect 'ἇι'.u do 'ᾇ'.u.foldcase end
  expect 'ἀι'.u do 'ᾈ'.u.foldcase end
  expect 'ἁι'.u do 'ᾉ'.u.foldcase end
  expect 'ἂι'.u do 'ᾊ'.u.foldcase end
  expect 'ἃι'.u do 'ᾋ'.u.foldcase end
  expect 'ἄι'.u do 'ᾌ'.u.foldcase end
  expect 'ἅι'.u do 'ᾍ'.u.foldcase end
  expect 'ἆι'.u do 'ᾎ'.u.foldcase end
  expect 'ἇι'.u do 'ᾏ'.u.foldcase end
  expect 'ἠι'.u do 'ᾐ'.u.foldcase end
  expect 'ἡι'.u do 'ᾑ'.u.foldcase end
  expect 'ἢι'.u do 'ᾒ'.u.foldcase end
  expect 'ἣι'.u do 'ᾓ'.u.foldcase end
  expect 'ἤι'.u do 'ᾔ'.u.foldcase end
  expect 'ἥι'.u do 'ᾕ'.u.foldcase end
  expect 'ἦι'.u do 'ᾖ'.u.foldcase end
  expect 'ἧι'.u do 'ᾗ'.u.foldcase end
  expect 'ἠι'.u do 'ᾘ'.u.foldcase end
  expect 'ἡι'.u do 'ᾙ'.u.foldcase end
  expect 'ἢι'.u do 'ᾚ'.u.foldcase end
  expect 'ἣι'.u do 'ᾛ'.u.foldcase end
  expect 'ἤι'.u do 'ᾜ'.u.foldcase end
  expect 'ἥι'.u do 'ᾝ'.u.foldcase end
  expect 'ἦι'.u do 'ᾞ'.u.foldcase end
  expect 'ἧι'.u do 'ᾟ'.u.foldcase end
  expect 'ὠι'.u do 'ᾠ'.u.foldcase end
  expect 'ὡι'.u do 'ᾡ'.u.foldcase end
  expect 'ὢι'.u do 'ᾢ'.u.foldcase end
  expect 'ὣι'.u do 'ᾣ'.u.foldcase end
  expect 'ὤι'.u do 'ᾤ'.u.foldcase end
  expect 'ὥι'.u do 'ᾥ'.u.foldcase end
  expect 'ὦι'.u do 'ᾦ'.u.foldcase end
  expect 'ὧι'.u do 'ᾧ'.u.foldcase end
  expect 'ὠι'.u do 'ᾨ'.u.foldcase end
  expect 'ὡι'.u do 'ᾩ'.u.foldcase end
  expect 'ὢι'.u do 'ᾪ'.u.foldcase end
  expect 'ὣι'.u do 'ᾫ'.u.foldcase end
  expect 'ὤι'.u do 'ᾬ'.u.foldcase end
  expect 'ὥι'.u do 'ᾭ'.u.foldcase end
  expect 'ὦι'.u do 'ᾮ'.u.foldcase end
  expect 'ὧι'.u do 'ᾯ'.u.foldcase end
  expect 'ὰι'.u do 'ᾲ'.u.foldcase end
  expect 'αι'.u do 'ᾳ'.u.foldcase end
  expect 'άι'.u do 'ᾴ'.u.foldcase end
  expect 'ᾶ'.u do 'ᾶ'.u.foldcase end
  expect 'ᾶι'.u do 'ᾷ'.u.foldcase end
  expect 'ᾰ'.u do 'Ᾰ'.u.foldcase end
  expect 'ᾱ'.u do 'Ᾱ'.u.foldcase end
  expect 'ὰ'.u do 'Ὰ'.u.foldcase end
  expect 'ά'.u do 'Ά'.u.foldcase end
  expect 'αι'.u do 'ᾼ'.u.foldcase end
  expect 'ι'.u do 'ι'.u.foldcase end
  expect 'ὴι'.u do 'ῂ'.u.foldcase end
  expect 'ηι'.u do 'ῃ'.u.foldcase end
  expect 'ήι'.u do 'ῄ'.u.foldcase end
  expect 'ῆ'.u do 'ῆ'.u.foldcase end
  expect 'ῆι'.u do 'ῇ'.u.foldcase end
  expect 'ὲ'.u do 'Ὲ'.u.foldcase end
  expect 'έ'.u do 'Έ'.u.foldcase end
  expect 'ὴ'.u do 'Ὴ'.u.foldcase end
  expect 'ή'.u do 'Ή'.u.foldcase end
  expect 'ηι'.u do 'ῌ'.u.foldcase end
  expect 'ῒ'.u do 'ῒ'.u.foldcase end
  expect 'ΐ'.u do 'ΐ'.u.foldcase end
  expect 'ῖ'.u do 'ῖ'.u.foldcase end
  expect 'ῗ'.u do 'ῗ'.u.foldcase end
  expect 'ῐ'.u do 'Ῐ'.u.foldcase end
  expect 'ῑ'.u do 'Ῑ'.u.foldcase end
  expect 'ὶ'.u do 'Ὶ'.u.foldcase end
  expect 'ί'.u do 'Ί'.u.foldcase end
  expect 'ῢ'.u do 'ῢ'.u.foldcase end
  expect 'ΰ'.u do 'ΰ'.u.foldcase end
  expect 'ῤ'.u do 'ῤ'.u.foldcase end
  expect 'ῦ'.u do 'ῦ'.u.foldcase end
  expect 'ῧ'.u do 'ῧ'.u.foldcase end
  expect 'ῠ'.u do 'Ῠ'.u.foldcase end
  expect 'ῡ'.u do 'Ῡ'.u.foldcase end
  expect 'ὺ'.u do 'Ὺ'.u.foldcase end
  expect 'ύ'.u do 'Ύ'.u.foldcase end
  expect 'ῥ'.u do 'Ῥ'.u.foldcase end
  expect 'ὼι'.u do 'ῲ'.u.foldcase end
  expect 'ωι'.u do 'ῳ'.u.foldcase end
  expect 'ώι'.u do 'ῴ'.u.foldcase end
  expect 'ῶ'.u do 'ῶ'.u.foldcase end
  expect 'ῶι'.u do 'ῷ'.u.foldcase end
  expect 'ὸ'.u do 'Ὸ'.u.foldcase end
  expect 'ό'.u do 'Ό'.u.foldcase end
  expect 'ὼ'.u do 'Ὼ'.u.foldcase end
  expect 'ώ'.u do 'Ώ'.u.foldcase end
  expect 'ωι'.u do 'ῼ'.u.foldcase end
  expect 'ω'.u do 'Ω'.u.foldcase end
  expect 'k'.u do 'K'.u.foldcase end
  expect 'å'.u do 'Å'.u.foldcase end
  expect 'ⅎ'.u do 'Ⅎ'.u.foldcase end
  expect 'ⅰ'.u do 'Ⅰ'.u.foldcase end
  expect 'ⅱ'.u do 'Ⅱ'.u.foldcase end
  expect 'ⅲ'.u do 'Ⅲ'.u.foldcase end
  expect 'ⅳ'.u do 'Ⅳ'.u.foldcase end
  expect 'ⅴ'.u do 'Ⅴ'.u.foldcase end
  expect 'ⅵ'.u do 'Ⅵ'.u.foldcase end
  expect 'ⅶ'.u do 'Ⅶ'.u.foldcase end
  expect 'ⅷ'.u do 'Ⅷ'.u.foldcase end
  expect 'ⅸ'.u do 'Ⅸ'.u.foldcase end
  expect 'ⅹ'.u do 'Ⅹ'.u.foldcase end
  expect 'ⅺ'.u do 'Ⅺ'.u.foldcase end
  expect 'ⅻ'.u do 'Ⅻ'.u.foldcase end
  expect 'ⅼ'.u do 'Ⅼ'.u.foldcase end
  expect 'ⅽ'.u do 'Ⅽ'.u.foldcase end
  expect 'ⅾ'.u do 'Ⅾ'.u.foldcase end
  expect 'ⅿ'.u do 'Ⅿ'.u.foldcase end
  expect 'ↄ'.u do 'Ↄ'.u.foldcase end
  expect 'ⓐ'.u do 'Ⓐ'.u.foldcase end
  expect 'ⓑ'.u do 'Ⓑ'.u.foldcase end
  expect 'ⓒ'.u do 'Ⓒ'.u.foldcase end
  expect 'ⓓ'.u do 'Ⓓ'.u.foldcase end
  expect 'ⓔ'.u do 'Ⓔ'.u.foldcase end
  expect 'ⓕ'.u do 'Ⓕ'.u.foldcase end
  expect 'ⓖ'.u do 'Ⓖ'.u.foldcase end
  expect 'ⓗ'.u do 'Ⓗ'.u.foldcase end
  expect 'ⓘ'.u do 'Ⓘ'.u.foldcase end
  expect 'ⓙ'.u do 'Ⓙ'.u.foldcase end
  expect 'ⓚ'.u do 'Ⓚ'.u.foldcase end
  expect 'ⓛ'.u do 'Ⓛ'.u.foldcase end
  expect 'ⓜ'.u do 'Ⓜ'.u.foldcase end
  expect 'ⓝ'.u do 'Ⓝ'.u.foldcase end
  expect 'ⓞ'.u do 'Ⓞ'.u.foldcase end
  expect 'ⓟ'.u do 'Ⓟ'.u.foldcase end
  expect 'ⓠ'.u do 'Ⓠ'.u.foldcase end
  expect 'ⓡ'.u do 'Ⓡ'.u.foldcase end
  expect 'ⓢ'.u do 'Ⓢ'.u.foldcase end
  expect 'ⓣ'.u do 'Ⓣ'.u.foldcase end
  expect 'ⓤ'.u do 'Ⓤ'.u.foldcase end
  expect 'ⓥ'.u do 'Ⓥ'.u.foldcase end
  expect 'ⓦ'.u do 'Ⓦ'.u.foldcase end
  expect 'ⓧ'.u do 'Ⓧ'.u.foldcase end
  expect 'ⓨ'.u do 'Ⓨ'.u.foldcase end
  expect 'ⓩ'.u do 'Ⓩ'.u.foldcase end
  expect 'ⰰ'.u do 'Ⰰ'.u.foldcase end
  expect 'ⰱ'.u do 'Ⰱ'.u.foldcase end
  expect 'ⰲ'.u do 'Ⰲ'.u.foldcase end
  expect 'ⰳ'.u do 'Ⰳ'.u.foldcase end
  expect 'ⰴ'.u do 'Ⰴ'.u.foldcase end
  expect 'ⰵ'.u do 'Ⰵ'.u.foldcase end
  expect 'ⰶ'.u do 'Ⰶ'.u.foldcase end
  expect 'ⰷ'.u do 'Ⰷ'.u.foldcase end
  expect 'ⰸ'.u do 'Ⰸ'.u.foldcase end
  expect 'ⰹ'.u do 'Ⰹ'.u.foldcase end
  expect 'ⰺ'.u do 'Ⰺ'.u.foldcase end
  expect 'ⰻ'.u do 'Ⰻ'.u.foldcase end
  expect 'ⰼ'.u do 'Ⰼ'.u.foldcase end
  expect 'ⰽ'.u do 'Ⰽ'.u.foldcase end
  expect 'ⰾ'.u do 'Ⰾ'.u.foldcase end
  expect 'ⰿ'.u do 'Ⰿ'.u.foldcase end
  expect 'ⱀ'.u do 'Ⱀ'.u.foldcase end
  expect 'ⱁ'.u do 'Ⱁ'.u.foldcase end
  expect 'ⱂ'.u do 'Ⱂ'.u.foldcase end
  expect 'ⱃ'.u do 'Ⱃ'.u.foldcase end
  expect 'ⱄ'.u do 'Ⱄ'.u.foldcase end
  expect 'ⱅ'.u do 'Ⱅ'.u.foldcase end
  expect 'ⱆ'.u do 'Ⱆ'.u.foldcase end
  expect 'ⱇ'.u do 'Ⱇ'.u.foldcase end
  expect 'ⱈ'.u do 'Ⱈ'.u.foldcase end
  expect 'ⱉ'.u do 'Ⱉ'.u.foldcase end
  expect 'ⱊ'.u do 'Ⱊ'.u.foldcase end
  expect 'ⱋ'.u do 'Ⱋ'.u.foldcase end
  expect 'ⱌ'.u do 'Ⱌ'.u.foldcase end
  expect 'ⱍ'.u do 'Ⱍ'.u.foldcase end
  expect 'ⱎ'.u do 'Ⱎ'.u.foldcase end
  expect 'ⱏ'.u do 'Ⱏ'.u.foldcase end
  expect 'ⱐ'.u do 'Ⱐ'.u.foldcase end
  expect 'ⱑ'.u do 'Ⱑ'.u.foldcase end
  expect 'ⱒ'.u do 'Ⱒ'.u.foldcase end
  expect 'ⱓ'.u do 'Ⱓ'.u.foldcase end
  expect 'ⱔ'.u do 'Ⱔ'.u.foldcase end
  expect 'ⱕ'.u do 'Ⱕ'.u.foldcase end
  expect 'ⱖ'.u do 'Ⱖ'.u.foldcase end
  expect 'ⱗ'.u do 'Ⱗ'.u.foldcase end
  expect 'ⱘ'.u do 'Ⱘ'.u.foldcase end
  expect 'ⱙ'.u do 'Ⱙ'.u.foldcase end
  expect 'ⱚ'.u do 'Ⱚ'.u.foldcase end
  expect 'ⱛ'.u do 'Ⱛ'.u.foldcase end
  expect 'ⱜ'.u do 'Ⱜ'.u.foldcase end
  expect 'ⱝ'.u do 'Ⱝ'.u.foldcase end
  expect 'ⱞ'.u do 'Ⱞ'.u.foldcase end
  expect 'ⱡ'.u do 'Ⱡ'.u.foldcase end
  expect 'ɫ'.u do 'Ɫ'.u.foldcase end
  expect 'ᵽ'.u do 'Ᵽ'.u.foldcase end
  expect 'ɽ'.u do 'Ɽ'.u.foldcase end
  expect 'ⱨ'.u do 'Ⱨ'.u.foldcase end
  expect 'ⱪ'.u do 'Ⱪ'.u.foldcase end
  expect 'ⱬ'.u do 'Ⱬ'.u.foldcase end
  expect 'ⱶ'.u do 'Ⱶ'.u.foldcase end
  expect 'ⲁ'.u do 'Ⲁ'.u.foldcase end
  expect 'ⲃ'.u do 'Ⲃ'.u.foldcase end
  expect 'ⲅ'.u do 'Ⲅ'.u.foldcase end
  expect 'ⲇ'.u do 'Ⲇ'.u.foldcase end
  expect 'ⲉ'.u do 'Ⲉ'.u.foldcase end
  expect 'ⲋ'.u do 'Ⲋ'.u.foldcase end
  expect 'ⲍ'.u do 'Ⲍ'.u.foldcase end
  expect 'ⲏ'.u do 'Ⲏ'.u.foldcase end
  expect 'ⲑ'.u do 'Ⲑ'.u.foldcase end
  expect 'ⲓ'.u do 'Ⲓ'.u.foldcase end
  expect 'ⲕ'.u do 'Ⲕ'.u.foldcase end
  expect 'ⲗ'.u do 'Ⲗ'.u.foldcase end
  expect 'ⲙ'.u do 'Ⲙ'.u.foldcase end
  expect 'ⲛ'.u do 'Ⲛ'.u.foldcase end
  expect 'ⲝ'.u do 'Ⲝ'.u.foldcase end
  expect 'ⲟ'.u do 'Ⲟ'.u.foldcase end
  expect 'ⲡ'.u do 'Ⲡ'.u.foldcase end
  expect 'ⲣ'.u do 'Ⲣ'.u.foldcase end
  expect 'ⲥ'.u do 'Ⲥ'.u.foldcase end
  expect 'ⲧ'.u do 'Ⲧ'.u.foldcase end
  expect 'ⲩ'.u do 'Ⲩ'.u.foldcase end
  expect 'ⲫ'.u do 'Ⲫ'.u.foldcase end
  expect 'ⲭ'.u do 'Ⲭ'.u.foldcase end
  expect 'ⲯ'.u do 'Ⲯ'.u.foldcase end
  expect 'ⲱ'.u do 'Ⲱ'.u.foldcase end
  expect 'ⲳ'.u do 'Ⲳ'.u.foldcase end
  expect 'ⲵ'.u do 'Ⲵ'.u.foldcase end
  expect 'ⲷ'.u do 'Ⲷ'.u.foldcase end
  expect 'ⲹ'.u do 'Ⲹ'.u.foldcase end
  expect 'ⲻ'.u do 'Ⲻ'.u.foldcase end
  expect 'ⲽ'.u do 'Ⲽ'.u.foldcase end
  expect 'ⲿ'.u do 'Ⲿ'.u.foldcase end
  expect 'ⳁ'.u do 'Ⳁ'.u.foldcase end
  expect 'ⳃ'.u do 'Ⳃ'.u.foldcase end
  expect 'ⳅ'.u do 'Ⳅ'.u.foldcase end
  expect 'ⳇ'.u do 'Ⳇ'.u.foldcase end
  expect 'ⳉ'.u do 'Ⳉ'.u.foldcase end
  expect 'ⳋ'.u do 'Ⳋ'.u.foldcase end
  expect 'ⳍ'.u do 'Ⳍ'.u.foldcase end
  expect 'ⳏ'.u do 'Ⳏ'.u.foldcase end
  expect 'ⳑ'.u do 'Ⳑ'.u.foldcase end
  expect 'ⳓ'.u do 'Ⳓ'.u.foldcase end
  expect 'ⳕ'.u do 'Ⳕ'.u.foldcase end
  expect 'ⳗ'.u do 'Ⳗ'.u.foldcase end
  expect 'ⳙ'.u do 'Ⳙ'.u.foldcase end
  expect 'ⳛ'.u do 'Ⳛ'.u.foldcase end
  expect 'ⳝ'.u do 'Ⳝ'.u.foldcase end
  expect 'ⳟ'.u do 'Ⳟ'.u.foldcase end
  expect 'ⳡ'.u do 'Ⳡ'.u.foldcase end
  expect 'ⳣ'.u do 'Ⳣ'.u.foldcase end
  expect 'ff'.u do 'ﬀ'.u.foldcase end
  expect 'fi'.u do 'ﬁ'.u.foldcase end
  expect 'fl'.u do 'ﬂ'.u.foldcase end
  expect 'ffi'.u do 'ﬃ'.u.foldcase end
  expect 'ffl'.u do 'ﬄ'.u.foldcase end
  expect 'st'.u do 'ﬅ'.u.foldcase end
  expect 'st'.u do 'ﬆ'.u.foldcase end
  expect 'մն'.u do 'ﬓ'.u.foldcase end
  expect 'մե'.u do 'ﬔ'.u.foldcase end
  expect 'մի'.u do 'ﬕ'.u.foldcase end
  expect 'վն'.u do 'ﬖ'.u.foldcase end
  expect 'մխ'.u do 'ﬗ'.u.foldcase end
  expect 'ａ'.u do 'Ａ'.u.foldcase end
  expect 'ｂ'.u do 'Ｂ'.u.foldcase end
  expect 'ｃ'.u do 'Ｃ'.u.foldcase end
  expect 'ｄ'.u do 'Ｄ'.u.foldcase end
  expect 'ｅ'.u do 'Ｅ'.u.foldcase end
  expect 'ｆ'.u do 'Ｆ'.u.foldcase end
  expect 'ｇ'.u do 'Ｇ'.u.foldcase end
  expect 'ｈ'.u do 'Ｈ'.u.foldcase end
  expect 'ｉ'.u do 'Ｉ'.u.foldcase end
  expect 'ｊ'.u do 'Ｊ'.u.foldcase end
  expect 'ｋ'.u do 'Ｋ'.u.foldcase end
  expect 'ｌ'.u do 'Ｌ'.u.foldcase end
  expect 'ｍ'.u do 'Ｍ'.u.foldcase end
  expect 'ｎ'.u do 'Ｎ'.u.foldcase end
  expect 'ｏ'.u do 'Ｏ'.u.foldcase end
  expect 'ｐ'.u do 'Ｐ'.u.foldcase end
  expect 'ｑ'.u do 'Ｑ'.u.foldcase end
  expect 'ｒ'.u do 'Ｒ'.u.foldcase end
  expect 'ｓ'.u do 'Ｓ'.u.foldcase end
  expect 'ｔ'.u do 'Ｔ'.u.foldcase end
  expect 'ｕ'.u do 'Ｕ'.u.foldcase end
  expect 'ｖ'.u do 'Ｖ'.u.foldcase end
  expect 'ｗ'.u do 'Ｗ'.u.foldcase end
  expect 'ｘ'.u do 'Ｘ'.u.foldcase end
  expect 'ｙ'.u do 'Ｙ'.u.foldcase end
  expect 'ｚ'.u do 'Ｚ'.u.foldcase end
  expect '𐐨'.u do '𐐀'.u.foldcase end
  expect '𐐩'.u do '𐐁'.u.foldcase end
  expect '𐐪'.u do '𐐂'.u.foldcase end
  expect '𐐫'.u do '𐐃'.u.foldcase end
  expect '𐐬'.u do '𐐄'.u.foldcase end
  expect '𐐭'.u do '𐐅'.u.foldcase end
  expect '𐐮'.u do '𐐆'.u.foldcase end
  expect '𐐯'.u do '𐐇'.u.foldcase end
  expect '𐐰'.u do '𐐈'.u.foldcase end
  expect '𐐱'.u do '𐐉'.u.foldcase end
  expect '𐐲'.u do '𐐊'.u.foldcase end
  expect '𐐳'.u do '𐐋'.u.foldcase end
  expect '𐐴'.u do '𐐌'.u.foldcase end
  expect '𐐵'.u do '𐐍'.u.foldcase end
  expect '𐐶'.u do '𐐎'.u.foldcase end
  expect '𐐷'.u do '𐐏'.u.foldcase end
  expect '𐐸'.u do '𐐐'.u.foldcase end
  expect '𐐹'.u do '𐐑'.u.foldcase end
  expect '𐐺'.u do '𐐒'.u.foldcase end
  expect '𐐻'.u do '𐐓'.u.foldcase end
  expect '𐐼'.u do '𐐔'.u.foldcase end
  expect '𐐽'.u do '𐐕'.u.foldcase end
  expect '𐐾'.u do '𐐖'.u.foldcase end
  expect '𐐿'.u do '𐐗'.u.foldcase end
  expect '𐑀'.u do '𐐘'.u.foldcase end
  expect '𐑁'.u do '𐐙'.u.foldcase end
  expect '𐑂'.u do '𐐚'.u.foldcase end
  expect '𐑃'.u do '𐐛'.u.foldcase end
  expect '𐑄'.u do '𐐜'.u.foldcase end
  expect '𐑅'.u do '𐐝'.u.foldcase end
  expect '𐑆'.u do '𐐞'.u.foldcase end
  expect '𐑇'.u do '𐐟'.u.foldcase end
  expect '𐑈'.u do '𐐠'.u.foldcase end
  expect '𐑉'.u do '𐐡'.u.foldcase end
  expect '𐑊'.u do '𐐢'.u.foldcase end
  expect '𐑋'.u do '𐐣'.u.foldcase end
  expect '𐑌'.u do '𐐤'.u.foldcase end
  expect '𐑍'.u do '𐐥'.u.foldcase end
  expect '𐑎'.u do '𐐦'.u.foldcase end
  expect '𐑏'.u do '𐐧'.u.foldcase end
end
